[package]
name = "cryptography-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.cryptography]
path = ".."

[[bin]]
name = "fuzz_aes"
path = "fuzz_targets/fuzz_aes.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_camellia"
path = "fuzz_targets/fuzz_camellia.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_cast128"
path = "fuzz_targets/fuzz_cast128.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_des"
path = "fuzz_targets/fuzz_des.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_grasshopper"
path = "fuzz_targets/fuzz_grasshopper.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_magma"
path = "fuzz_targets/fuzz_magma.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_present"
path = "fuzz_targets/fuzz_present.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_seed"
path = "fuzz_targets/fuzz_seed.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_serpent"
path = "fuzz_targets/fuzz_serpent.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_simon"
path = "fuzz_targets/fuzz_simon.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_sm4"
path = "fuzz_targets/fuzz_sm4.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_speck"
path = "fuzz_targets/fuzz_speck.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_twofish"
path = "fuzz_targets/fuzz_twofish.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_chacha20"
path = "fuzz_targets/fuzz_chacha20.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_rabbit"
path = "fuzz_targets/fuzz_rabbit.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_salsa20"
path = "fuzz_targets/fuzz_salsa20.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_snow3g"
path = "fuzz_targets/fuzz_snow3g.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_zuc"
path = "fuzz_targets/fuzz_zuc.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_ml_kem"
path = "fuzz_targets/fuzz_ml_kem.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_ml_dsa"
path = "fuzz_targets/fuzz_ml_dsa.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_pk_parse"
path = "fuzz_targets/fuzz_pk_parse.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_ed25519"
path = "fuzz_targets/fuzz_ed25519.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_ecdsa"
path = "fuzz_targets/fuzz_ecdsa.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_eddsa"
path = "fuzz_targets/fuzz_eddsa.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_ecdh"
path = "fuzz_targets/fuzz_ecdh.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_dsa"
path = "fuzz_targets/fuzz_dsa.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_dh"
path = "fuzz_targets/fuzz_dh.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_elgamal"
path = "fuzz_targets/fuzz_elgamal.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_ec_elgamal"
path = "fuzz_targets/fuzz_ec_elgamal.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_edwards_elgamal"
path = "fuzz_targets/fuzz_edwards_elgamal.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_paillier"
path = "fuzz_targets/fuzz_paillier.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_rabin"
path = "fuzz_targets/fuzz_rabin.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_cocks"
path = "fuzz_targets/fuzz_cocks.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_schmidt_samoa"
path = "fuzz_targets/fuzz_schmidt_samoa.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_ecies"
path = "fuzz_targets/fuzz_ecies.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_rsa_pkcs1"
path = "fuzz_targets/fuzz_rsa_pkcs1.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_hash"
path = "fuzz_targets/fuzz_hash.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_modes"
path = "fuzz_targets/fuzz_modes.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_cprng"
path = "fuzz_targets/fuzz_cprng.rs"
test = false
doc = false
bench = false
