//! Digital Signature Algorithm (`DSA`), as FIPS 186-4 specifies it
//! (`pubs/fips186-4.pdf`). FIPS 186-5 no longer approves `DSA` for generating
//! signatures and allows it only for verifying signatures made earlier; its
//! specification now exists only in FIPS 186-4.
//!
//! `DSA` works in a prime-order subgroup: a prime modulus `p`, a prime
//! subgroup order `q` dividing `p - 1`, and a generator `g` of the order-`q`
//! subgroup — the domain parameters. Signing and verification then operate
//! entirely modulo `q`, while the group actions still happen modulo `p`.
//!
//! What follows FIPS 186-4, and what does not:
//!
//! - [`Dsa::generate_params`] generates domain parameters by Appendix A.1.1.2
//!   (`p` and `q`) and A.2.3 (`g`, with `index = 1`, A.2.3's own example value
//!   for digital signatures) at the four `(L, N)` pairs of §4.2, and keeps the
//!   seed record that A.1.1.3 and A.2.4 validate ([`DsaParams::with_seed`]).
//! - [`Dsa::generate`] draws the private key `x` uniformly from `[1, q − 1]`,
//!   the distribution of Appendix B.1.2 (key pair generation by testing
//!   candidates).
//! - [`DsaPrivateKey::sign_digest_with_rng`] draws the per-message `k`
//!   uniformly from `[1, q − 1]`, the distribution of Appendix B.2.2, and
//!   computes `r` and `s` as §4.6 does, drawing a new `k` if either is zero.
//! - [`DsaPublicKey::verify`] is §4.7, including step 1's range check on `r`
//!   and `s`; digests are cut to their leftmost `min(N, outlen)` bits.
//! - [`DsaPrivateKey::sign_digest`] derives `k` deterministically by RFC 6979.
//!   FIPS 186-4 Appendix B.2 allows only its two random methods "or another
//!   approved method", and RFC 6979 is not one: those signatures verify under
//!   FIPS 186-4 but are not generated by it.
//! - [`Dsa::generate_toy_params`] makes groups smaller than any size FIPS
//!   186-4 defines, for tests, and [`Dsa::from_secret_exponent`] accepts any
//!   valid group; neither is FIPS 186-4 unless its inputs are. Every group,
//!   standard or not, must have `q ≥ 2^15` and `p` of at most 16384 bits
//!   ([`MIN_SUBGROUP_ORDER_BITS`], [`MAX_MODULUS_BITS`],
//!   [`MAX_SUBGROUP_ORDER_BITS`]).
//! - Both signers give up after [`MAX_NONCE_DRAWS`] rejected `k` and return
//!   `None`; a working source and a valid group never reach that bound.
//!
//! ## Timing
//!
//! The modular exponentiations are rump's, which are variable-time: the
//! number of multiplications in `g^k mod p` follows the bit length and
//! Hamming weight of the exponent. Signing therefore leaks the bit length of
//! the per-message secret `k` through its running time, and the lattice
//! attacks on DSA recover `x` from a few bits of many `k`s. `x` itself enters
//! signing only through the multiplication `x·r mod q`, whose cost does not
//! depend on `x`'s value beyond its length. Verification handles no secret.
//! Nothing here is safe against an adversary who can time the signer.
//!
//! [`MIN_SUBGROUP_ORDER_BITS`]: crate::public_key::primes::MIN_SUBGROUP_ORDER_BITS
//! [`MAX_MODULUS_BITS`]: crate::public_key::primes::MAX_MODULUS_BITS
//! [`MAX_SUBGROUP_ORDER_BITS`]: crate::public_key::primes::MAX_SUBGROUP_ORDER_BITS
//!
//! ## Key encodings
//!
//! The crate-defined `to_key_blob`, `to_pem` and `to_xml` forms remain the
//! defaults. The standard encodings sit beside them:
//! [`DsaPublicKey::to_spki_der`] (RFC 3279 §2.3.2 `SubjectPublicKeyInfo`, PEM
//! label `PUBLIC KEY`), [`DsaPrivateKey::to_pkcs8_der`] (RFC 5958
//! `OneAsymmetricKey`, whose §2 gives a DSA private key as an `INTEGER`; PEM
//! label `PRIVATE KEY`) and [`DsaParams::to_der`] (`Dss-Parms`), each with a
//! decoder.

use core::fmt;

use crate::hash::Digest;
use crate::public_key::io::{decode_biguints, encode_biguints};
use crate::public_key::primes::{
    impl_ffc_params, is_in_prime_order_subgroup, random_nonzero_below, validate_prime_order_group,
    FfcDomain, FfcHash, FfcParameterSize, PrimalityPolicy, MAX_NONCE_DRAWS,
};
use crate::public_key::rfc6979::{bits_to_int, NonceGenerator};
use crate::Csprng;
use rump::modular::{mod_inverse, mod_pow, MontgomeryContext};
use rump::BigUint;

const DSA_PUBLIC_LABEL: &str = "CRYPTOGRAPHY DSA PUBLIC KEY";
const DSA_PRIVATE_LABEL: &str = "CRYPTOGRAPHY DSA PRIVATE KEY";
const DSA_PARAMS_LABEL: &str = "CRYPTOGRAPHY DSA PARAMETERS";

/// The FIPS 186-4 A.2.3 `index` of the generators [`Dsa::generate_params`]
/// derives: the value A.2.3 gives as its example for digital signatures.
const DIGITAL_SIGNATURE_INDEX: u8 = 1;

/// `DSA` domain parameters `(p, q, g {, seed record})`.
///
/// Many key pairs can share one set. Every instance was generated here or
/// validated on the way in ([`DsaParams::new`], [`DsaParams::with_seed`], the
/// parsers), which is why the fields are private. Parameters from
/// [`Dsa::generate_params`] or [`DsaParams::with_seed`] carry the FIPS 186-4
/// seed record a third party needs to validate them ([`DsaParams::seed`]);
/// others carry none.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DsaParams {
    domain: FfcDomain,
}

/// Public key for `DSA`.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DsaPublicKey {
    /// Prime modulus `p`.
    p: BigUint,
    /// Prime subgroup order `q`.
    q: BigUint,
    /// Generator `g` of the order-`q` subgroup.
    g: BigUint,
    /// Public component `y = g^x mod p`.
    y: BigUint,
    /// Cached Montgomery context for arithmetic modulo `p`.
    p_ctx: Option<MontgomeryContext>,
    /// Cached Montgomery context for arithmetic modulo `q`.
    q_ctx: Option<MontgomeryContext>,
}

/// Private key for `DSA`.
#[derive(Clone, Eq, PartialEq)]
pub struct DsaPrivateKey {
    /// Prime modulus `p`.
    p: BigUint,
    /// Prime subgroup order `q`.
    q: BigUint,
    /// Generator `g` of the order-`q` subgroup.
    g: BigUint,
    /// Secret exponent `x`.
    x: BigUint,
    /// Cached public component `y = g^x mod p`.
    y: BigUint,
    /// Cached Montgomery context for arithmetic modulo `p`.
    p_ctx: Option<MontgomeryContext>,
    /// Cached Montgomery context for arithmetic modulo `q`.
    q_ctx: Option<MontgomeryContext>,
}

/// Raw `DSA` signature pair `(r, s)`.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DsaSignature {
    r: BigUint,
    s: BigUint,
}

/// Namespace wrapper for the `DSA` construction.
pub struct Dsa;

impl_ffc_params!(DsaParams, DSA_PARAMS_LABEL, "DsaParams", "`DSA`");
crate::public_key::ffc_pkix::impl_ffc_parameters_der!(
    DsaParams,
    Dsa,
    "Encode as RFC 3279 §2.3.2 `Dss-Parms ::= SEQUENCE { p, q, g }` in DER. \
     `Dss-Parms` has no field for the FIPS 186-4 seed record, so none is written.",
    "Decode `Dss-Parms` in strict DER, validating the group as [`Self::new`] \
     does. The result carries no seed record."
);

impl DsaPublicKey {
    /// Return the prime modulus.
    #[must_use]
    pub fn modulus(&self) -> &BigUint {
        &self.p
    }

    /// Return the prime subgroup order.
    #[must_use]
    pub fn subgroup_order(&self) -> &BigUint {
        &self.q
    }

    /// Return the subgroup generator.
    #[must_use]
    pub fn generator(&self) -> &BigUint {
        &self.g
    }

    /// Return the public component `y = g^x mod p`.
    #[must_use]
    pub fn public_component(&self) -> &BigUint {
        &self.y
    }

    /// A public key from validated domain parameters and the public
    /// component `y`.
    ///
    /// `y` must lie in the order-`q` subgroup: `1 < y < p` and
    /// `y^q ≡ 1 (mod p)`, the FFC full public-key validation of SP 800-56A
    /// Rev. 3 §5.6.2.3.1 (FIPS 186-4 leaves public-key assurance to SP
    /// 800-89). Returns `None` otherwise. The group itself was validated when
    /// `params` was built, so nothing about it is recomputed here.
    #[must_use]
    pub fn from_public_component(params: &DsaParams, y: BigUint) -> Option<Self> {
        let (p, q, g) = (
            params.modulus(),
            params.subgroup_order(),
            params.generator(),
        );
        if !is_in_prime_order_subgroup(&y, q, p) {
            return None;
        }
        Some(Self {
            p: p.clone(),
            q: q.clone(),
            g: g.clone(),
            y,
            p_ctx: MontgomeryContext::new(p).ok(),
            q_ctx: MontgomeryContext::new(q).ok(),
        })
    }

    /// Extract the domain parameters `(p, q, g)` as a standalone
    /// [`DsaParams`], suitable for generating further key pairs in the group.
    ///
    /// A parsed public key has had only the structural (fixed-base) checks,
    /// but a `DsaParams` is a group this crate will generate secrets over, so
    /// this runs the hardened validation of [`DsaParams::new`] and returns
    /// `None` if the parameters do not survive it. Keys store no seed record,
    /// so the parameters returned have none.
    #[must_use]
    pub fn params(&self) -> Option<DsaParams> {
        DsaParams::new(self.p.clone(), self.q.clone(), self.g.clone())
    }

    /// Hash one message with `H`, then verify the resulting digest.
    #[must_use]
    pub fn verify_message<H: Digest>(&self, message: &[u8], signature: &DsaSignature) -> bool {
        let digest = H::digest(message);
        self.verify(&digest, signature)
    }

    /// Hash one message with `H`, then verify a serialized signature.
    #[must_use]
    pub fn verify_message_bytes<H: Digest>(&self, message: &[u8], signature: &[u8]) -> bool {
        let digest = H::digest(message);
        self.verify_bytes(&digest, signature)
    }

    /// Verify a signature over an explicit integer representative.
    #[must_use]
    pub fn verify_digest_scalar(&self, hash: &BigUint, signature: &DsaSignature) -> bool {
        if signature.r.is_zero()
            || signature.s.is_zero()
            || signature.r >= self.q
            || signature.s >= self.q
        {
            return false;
        }

        let Some(w) = mod_inverse(&signature.s, &self.q) else {
            return false;
        };
        // FIPS 186-4 verification variables: `w = s^-1 mod q`,
        // `z = leftmost-N-bits(H(M)) mod q`, then `u1 = z * w mod q` and
        // `u2 = r * w mod q`.
        let z = hash.rem(&self.q);
        let u1 = if let Some(ctx) = &self.q_ctx {
            ctx.mul(&z, &w)
        } else {
            BigUint::mod_mul(&z, &w, &self.q)
        };
        let u2 = if let Some(ctx) = &self.q_ctx {
            ctx.mul(&signature.r, &w)
        } else {
            BigUint::mod_mul(&signature.r, &w, &self.q)
        };

        let g_term = if let Some(ctx) = &self.p_ctx {
            ctx.pow(&self.g, &u1)
        } else {
            mod_pow(&self.g, &u1, &self.p)
        };
        let y_term = if let Some(ctx) = &self.p_ctx {
            ctx.pow(&self.y, &u2)
        } else {
            mod_pow(&self.y, &u2, &self.p)
        };
        let combined = if let Some(ctx) = &self.p_ctx {
            ctx.mul(&g_term, &y_term)
        } else {
            BigUint::mod_mul(&g_term, &y_term, &self.p)
        };

        combined.rem(&self.q) == signature.r
    }

    /// Verify a signature over the provided digest bytes.
    ///
    /// The digest is cut to its leftmost `min(N, outlen)` bits, `N = bits(q)`,
    /// as FIPS 186-4 §4.7 step 2 computes `z`.
    #[must_use]
    pub fn verify(&self, digest: &[u8], signature: &DsaSignature) -> bool {
        self.verify_digest_scalar(&digest_to_scalar(digest, &self.q), signature)
    }

    /// Verify a byte-encoded signature produced by
    /// [`DsaPrivateKey::sign_digest_bytes`].
    #[must_use]
    pub fn verify_bytes(&self, digest: &[u8], signature: &[u8]) -> bool {
        let Some(signature) = DsaSignature::from_key_blob(signature) else {
            return false;
        };
        self.verify(digest, &signature)
    }

    /// Schema fields for the crate-defined serialization formats.
    fn serial_fields(&self) -> Vec<BigUint> {
        vec![
            self.p.clone(),
            self.q.clone(),
            self.g.clone(),
            self.y.clone(),
        ]
    }

    /// Validate schema fields and rebuild the key with its derived state.
    ///
    /// Structural validation (public material): fixed-base primality of `p`
    /// and `q`, the subgroup relations for `g`, and `y` in the order-`q`
    /// subgroup (`1 < y < p`, `y^q ≡ 1 (mod p)`). For odd `q` the check on `y`
    /// is the FFC full public-key validation of SP 800-56A Rev. 3 §5.6.2.3.1;
    /// FIPS 186-4 leaves the assurance of public-key validity to SP 800-89.
    fn from_serial_fields(fields: Vec<BigUint>) -> Option<Self> {
        let mut fields = fields.into_iter();
        let p = fields.next()?;
        let q = fields.next()?;
        let g = fields.next()?;
        let y = fields.next()?;
        if !validate_prime_order_group(&p, &q, &g, PrimalityPolicy::Structural)
            || !is_in_prime_order_subgroup(&y, &q, &p)
        {
            return None;
        }
        let p_ctx = MontgomeryContext::new(&p).ok();
        let q_ctx = MontgomeryContext::new(&q).ok();
        Some(Self {
            p,
            q,
            g,
            y,
            p_ctx,
            q_ctx,
        })
    }
}

crate::public_key::io::impl_xml_serialization!(DsaPublicKey, "DsaPublicKey", ["p", "q", "g", "y"]);
crate::public_key::io::impl_blob_pem_serialization!(
    DsaPublicKey,
    DSA_PUBLIC_LABEL,
    ["p", "q", "g", "y"]
);

impl DsaPrivateKey {
    /// Return the prime modulus.
    #[must_use]
    pub fn modulus(&self) -> &BigUint {
        &self.p
    }

    /// Return the prime subgroup order.
    #[must_use]
    pub fn subgroup_order(&self) -> &BigUint {
        &self.q
    }

    /// Return the subgroup generator.
    #[must_use]
    pub fn generator(&self) -> &BigUint {
        &self.g
    }

    /// Return the private exponent `x`.
    #[must_use]
    pub fn exponent(&self) -> &BigUint {
        &self.x
    }

    /// Extract the domain parameters `(p, q, g)` as a standalone
    /// [`DsaParams`], suitable for generating further key pairs in the group.
    ///
    /// A private key's group has already passed the hardened validation (at
    /// generation or at parse time), so no further check is needed. Keys store
    /// no seed record, so the parameters returned have none.
    #[must_use]
    pub fn params(&self) -> DsaParams {
        DsaParams::from_domain(FfcDomain::from_validated_parts(
            self.p.clone(),
            self.q.clone(),
            self.g.clone(),
        ))
    }

    /// Derive the matching public key from this private key.
    #[must_use]
    pub fn to_public_key(&self) -> DsaPublicKey {
        DsaPublicKey {
            p: self.p.clone(),
            q: self.q.clone(),
            g: self.g.clone(),
            y: self.y.clone(),
            p_ctx: self.p_ctx.clone(),
            q_ctx: self.q_ctx.clone(),
        }
    }

    /// Sign with an explicit nonce `k`.
    ///
    /// `DSA` uses a fresh `k` in `[1, q)` for every signature. This lower-level
    /// entry point keeps the arithmetic explicit for deterministic tests.
    ///
    /// Reusing the same `k` for two different messages with the same key
    /// immediately reveals the private exponent. Outside of fixed vectors,
    /// prefer [`Self::sign_digest`] or [`Self::sign_message`].
    #[must_use]
    pub fn sign_digest_with_nonce(&self, digest: &[u8], nonce: &BigUint) -> Option<DsaSignature> {
        if nonce.is_zero() || nonce >= &self.q {
            return None;
        }

        let z = digest_to_scalar(digest, &self.q);
        let r = if let Some(ctx) = &self.p_ctx {
            ctx.pow(&self.g, nonce)
        } else {
            mod_pow(&self.g, nonce, &self.p)
        }
        .rem(&self.q);
        if r.is_zero() {
            return None;
        }

        let nonce_inv = mod_inverse(nonce, &self.q)?;
        let xr = if let Some(ctx) = &self.q_ctx {
            ctx.mul(&self.x, &r)
        } else {
            BigUint::mod_mul(&self.x, &r, &self.q)
        };
        let sum = z.add(&xr).rem(&self.q);
        let s = if let Some(ctx) = &self.q_ctx {
            ctx.mul(&nonce_inv, &sum)
        } else {
            BigUint::mod_mul(&nonce_inv, &sum, &self.q)
        };
        if s.is_zero() {
            return None;
        }

        Some(DsaSignature { r, s })
    }

    /// Sign a pre-hashed digest using RFC 6979 deterministic nonce derivation.
    ///
    /// A `k` that gives `r = 0` or `s = 0` is rejected and the next candidate
    /// of RFC 6979 §3.2 step h.3 taken, as §3.2 prescribes; after
    /// [`MAX_NONCE_DRAWS`] rejected candidates this returns `None` instead of
    /// continuing. Every `k` is rejected only in a group whose subgroup
    /// consists of `1` and multiples of `q` — the order-2 subgroup
    /// `{1, p − 1}` — which the size policy (`q ≥ 2^15`) excludes, so for a
    /// key this crate built or parsed the bound is never reached.
    #[must_use]
    pub fn sign_digest<H: Digest>(&self, digest: &[u8]) -> Option<DsaSignature> {
        let mut nonces = NonceGenerator::<H>::new(&self.q, &self.x, digest)?;
        (0..MAX_NONCE_DRAWS).find_map(|_| self.sign_digest_with_nonce(digest, &nonces.next()))
    }

    /// Sign a digest using a fresh random nonce `k` in `[1, q)` from `rng`.
    ///
    /// FIPS 186-4 §4.6 has signing draw a new `k` whenever `r = 0` or
    /// `s = 0`. A working random source is rejected with probability about
    /// `2/q` per draw, so this returns after the first draw in practice and
    /// returns `None` only after [`MAX_NONCE_DRAWS`] consecutive draws have
    /// all been rejected: probability about `(2/q)^64` for a working source,
    /// and the signature of a source that repeats an in-range `k` this key
    /// and digest reject.
    ///
    /// # Panics
    ///
    /// Panics on a source that stalls below the range — one that repeats a
    /// value the sampler itself rejects for 256 draws — as
    /// [`random_nonzero_below`] does; that report comes before this
    /// function's own bound can.
    #[must_use]
    pub fn sign_digest_with_rng<R: Csprng>(
        &self,
        digest: &[u8],
        rng: &mut R,
    ) -> Option<DsaSignature> {
        (0..MAX_NONCE_DRAWS).find_map(|_| {
            let nonce = random_nonzero_below(rng, &self.q)?;
            self.sign_digest_with_nonce(digest, &nonce)
        })
    }

    /// Hash one message with `H`, then sign deterministically.
    #[must_use]
    pub fn sign_message<H: Digest>(&self, message: &[u8]) -> Option<DsaSignature> {
        let digest = H::digest(message);
        self.sign_digest::<H>(&digest)
    }

    /// Hash one message with `H`, then sign with randomized nonces.
    #[must_use]
    pub fn sign_message_with_rng<H: Digest, R: Csprng>(
        &self,
        message: &[u8],
        rng: &mut R,
    ) -> Option<DsaSignature> {
        let digest = H::digest(message);
        self.sign_digest_with_rng(&digest, rng)
    }

    /// Sign a digest deterministically and return serialized signature bytes.
    #[must_use]
    pub fn sign_digest_bytes<H: Digest>(&self, digest: &[u8]) -> Option<Vec<u8>> {
        let signature = self.sign_digest::<H>(digest)?;
        Some(signature.to_key_blob())
    }

    /// Sign a digest with randomized nonces and return serialized signature bytes.
    #[must_use]
    pub fn sign_digest_bytes_with_rng<H: Digest, R: Csprng>(
        &self,
        digest: &[u8],
        rng: &mut R,
    ) -> Option<Vec<u8>> {
        let signature = self.sign_digest_with_rng(digest, rng)?;
        Some(signature.to_key_blob())
    }

    /// Hash one message with `H`, then sign and serialize deterministically.
    #[must_use]
    pub fn sign_message_bytes<H: Digest>(&self, message: &[u8]) -> Option<Vec<u8>> {
        let signature = self.sign_message::<H>(message)?;
        Some(signature.to_key_blob())
    }

    /// Hash one message with `H`, then sign and serialize with randomized nonces.
    #[must_use]
    pub fn sign_message_bytes_with_rng<H: Digest, R: Csprng>(
        &self,
        message: &[u8],
        rng: &mut R,
    ) -> Option<Vec<u8>> {
        let signature = self.sign_message_with_rng::<H, R>(message, rng)?;
        Some(signature.to_key_blob())
    }

    /// Schema fields for the crate-defined serialization formats.
    fn serial_fields(&self) -> Vec<BigUint> {
        vec![
            self.p.clone(),
            self.q.clone(),
            self.g.clone(),
            self.x.clone(),
        ]
    }

    /// Validate schema fields and rebuild the key with its derived state.
    ///
    /// Full validation (private material): hardened primality of `p` and
    /// `q`, the subgroup relations for `g`, `x ∈ [1, q)`, and `y` recomputed
    /// from `x` rather than carried.
    fn from_serial_fields(fields: Vec<BigUint>) -> Option<Self> {
        let mut fields = fields.into_iter();
        let p = fields.next()?;
        let q = fields.next()?;
        let g = fields.next()?;
        let x = fields.next()?;
        if !validate_prime_order_group(&p, &q, &g, PrimalityPolicy::Hardened)
            || x.is_zero()
            || x >= q
        {
            return None;
        }
        Some(Dsa::key_pair(&p, &q, &g, x).1)
    }
}

crate::public_key::io::impl_xml_serialization!(
    DsaPrivateKey,
    "DsaPrivateKey",
    ["p", "q", "g", "x"]
);
crate::public_key::io::impl_blob_pem_serialization!(
    DsaPrivateKey,
    DSA_PRIVATE_LABEL,
    ["p", "q", "g", "x"]
);
crate::public_key::ffc_pkix::impl_ffc_key_encodings!(
    DsaPublicKey,
    DsaPrivateKey,
    Dsa,
    "RFC 3279 §2.3.2, `id-dsa` with `Dss-Parms` and the `DSAPublicKey` \
     `INTEGER` `y`",
    "RFC 5958 §2 gives a DSA private key as an `INTEGER`: the algorithm is \
     `id-dsa` with `Dss-Parms` (RFC 3279 §2.3.2), and `privateKey` holds `x`."
);

impl fmt::Debug for DsaPrivateKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("DsaPrivateKey(<redacted>)")
    }
}

impl DsaSignature {
    /// Return the first signature component.
    #[must_use]
    pub fn r(&self) -> &BigUint {
        &self.r
    }

    /// Return the second signature component.
    #[must_use]
    pub fn s(&self) -> &BigUint {
        &self.s
    }

    /// Encode as the X9.62 / RFC 3279 §2.2.2 `Dss-Sig-Value`:
    /// `SEQUENCE { r INTEGER, s INTEGER }` in strict DER.
    #[must_use]
    pub fn to_der(&self) -> Vec<u8> {
        encode_biguints(&[&self.r, &self.s])
    }

    /// Decode a `Dss-Sig-Value`.
    ///
    /// Strict DER only. Zero components are rejected here; the range check
    /// against the subgroup order `q` happens during verification because
    /// the structure does not carry `q`.
    #[must_use]
    pub fn from_der(der: &[u8]) -> Option<Self> {
        let mut fields = decode_biguints(der)?.into_iter();
        let r = fields.next()?;
        let s = fields.next()?;
        if fields.next().is_some() || r.is_zero() || s.is_zero() {
            return None;
        }
        Some(Self { r, s })
    }

    /// The crate-defined signature blob, byte-identical to [`Self::to_der`].
    #[must_use]
    pub fn to_key_blob(&self) -> Vec<u8> {
        self.to_der()
    }

    /// Decode the crate-defined signature blob; identical to
    /// [`Self::from_der`].
    #[must_use]
    pub fn from_key_blob(blob: &[u8]) -> Option<Self> {
        Self::from_der(blob)
    }
}

impl Dsa {
    /// Derive a `DSA` key pair from explicit subgroup parameters and secret
    /// exponent: the parameters go through [`DsaParams::new`] — a group this
    /// crate signs under with the caller's secret gets the hardened
    /// validation — and the key pair through [`Dsa::with_secret_exponent`].
    #[must_use]
    pub fn from_secret_exponent(
        prime: &BigUint,
        subgroup_order: &BigUint,
        generator: &BigUint,
        secret: &BigUint,
    ) -> Option<(DsaPublicKey, DsaPrivateKey)> {
        let params = DsaParams::new(prime.clone(), subgroup_order.clone(), generator.clone())?;
        Self::with_secret_exponent(&params, secret)
    }

    /// Derive a `DSA` key pair from validated domain parameters and the
    /// secret exponent `x`. Returns `None` unless `x ∈ [1, q − 1]`, the range
    /// FIPS 186-4 §4.1 gives it; `y = g^x mod p` is computed here.
    #[must_use]
    pub fn with_secret_exponent(
        params: &DsaParams,
        secret: &BigUint,
    ) -> Option<(DsaPublicKey, DsaPrivateKey)> {
        let (p, q, g) = (
            params.modulus(),
            params.subgroup_order(),
            params.generator(),
        );
        if secret.is_zero() || secret >= q {
            return None;
        }
        Some(Self::key_pair(p, q, g, secret.clone()))
    }

    /// The key pair of the secret `x ∈ [1, q)` over a validated group, with
    /// its cached Montgomery contexts.
    fn key_pair(
        p: &BigUint,
        q: &BigUint,
        g: &BigUint,
        x: BigUint,
    ) -> (DsaPublicKey, DsaPrivateKey) {
        let p_ctx = MontgomeryContext::new(p).ok();
        let q_ctx = MontgomeryContext::new(q).ok();
        let y = match &p_ctx {
            Some(ctx) => ctx.pow(g, &x),
            None => mod_pow(g, &x, p),
        };
        (
            DsaPublicKey {
                p: p.clone(),
                q: q.clone(),
                g: g.clone(),
                y: y.clone(),
                p_ctx: p_ctx.clone(),
                q_ctx: q_ctx.clone(),
            },
            DsaPrivateKey {
                p: p.clone(),
                q: q.clone(),
                g: g.clone(),
                x,
                y,
                p_ctx,
                q_ctx,
            },
        )
    }

    /// Generate `DSA` domain parameters by FIPS 186-4: `p` and `q` by
    /// Appendix A.1.1.2 with `hash` and an `N`-bit seed drawn from `rng`, then
    /// `g` by A.2.3 with index 1. The parameters carry their seed record, so
    /// any FIPS 186-4 validator — [`DsaParams::with_seed`] among them — can
    /// check them.
    ///
    /// `size` is one of the §4.2 pairs. Returns `None` if `hash` is shorter
    /// than `N` bits (A.1.1.2): SHA-224 serves only `N = 160` and `N = 224`.
    ///
    /// # Panics
    ///
    /// Panics on a source that stalls, as the primality test's base sampler
    /// ([`random_below`](crate::public_key::primes::random_below)) does after
    /// 256 consecutive rejected draws.
    #[must_use]
    pub fn generate_params<R: Csprng>(
        rng: &mut R,
        size: FfcParameterSize,
        hash: FfcHash,
    ) -> Option<DsaParams> {
        FfcDomain::generate_fips186_4(rng, size, hash, DIGITAL_SIGNATURE_INDEX)
            .map(DsaParams::from_domain)
    }

    /// Generate a small group for tests. **This is not FIPS 186-4**: the sizes
    /// are ones §4.2 does not list, and the construction follows no standard.
    ///
    /// Accepts `bits` from 19 to 1023 and returns `None` otherwise, so every
    /// size FIPS 186-4 covers goes through [`Dsa::generate_params`]. The
    /// subgroup order has `clamp(⌊bits/4⌋, 16, 256)` bits, `p = kq + 1` for a
    /// random even `k`, and `g = h^k mod p` for a random `h`. No seed is kept:
    /// the parameters can be checked for structure, not for how they were made.
    ///
    /// # Panics
    ///
    /// Panics on a stalled or constant source, as the prime and cofactor
    /// samplers do (see
    /// [`random_probable_prime`](crate::public_key::primes::random_probable_prime)).
    #[must_use]
    pub fn generate_toy_params<R: Csprng>(rng: &mut R, bits: usize) -> Option<DsaParams> {
        FfcDomain::generate_toy(rng, bits).map(DsaParams::from_domain)
    }

    /// Generate a `DSA` key pair from existing domain parameters.
    ///
    /// `x` is uniform on `[1, q − 1]`, the distribution FIPS 186-4 Appendix
    /// B.1.2 produces for parameters of an approved size.
    ///
    /// # Panics
    ///
    /// Panics on a source that stalls, as [`random_nonzero_below`] does
    /// after 256 consecutive rejected draws.
    #[must_use]
    pub fn generate<R: Csprng>(params: &DsaParams, rng: &mut R) -> (DsaPublicKey, DsaPrivateKey) {
        let (p, q, g) = (
            params.modulus(),
            params.subgroup_order(),
            params.generator(),
        );
        // Every `DsaParams` has a prime subgroup order q >= 2^15, so `[1, q)`
        // is never empty.
        let secret = random_nonzero_below(rng, q)
            .expect("validated DSA parameters have a prime subgroup order q >= 2^15");
        Self::key_pair(p, q, g, secret)
    }
}

/// FIPS 186-4 digest representative reduction.
///
/// §4.6 and §4.7 keep the leftmost `min(N, outlen)` bits of the hash, with
/// `N = bits(q)`. The shift amount is derived from the original digest width,
/// not the width after leading-zero trimming.
fn digest_to_scalar(digest: &[u8], modulus: &BigUint) -> BigUint {
    bits_to_int(digest, modulus.bits())
}

#[cfg(test)]
mod tests {
    use super::{Dsa, DsaParams, DsaPrivateKey, DsaPublicKey, DsaSignature, DSA_PARAMS_LABEL};
    use crate::public_key::io::{encode_biguints, pem_wrap};
    use crate::public_key::primes::{cavp, FfcHash, FfcParameterSize, MAX_NONCE_DRAWS};
    use crate::test_utils::decode_hex;
    use crate::{CtrDrbgAes256, Sha256, Sha384};
    use rump::modular::MontgomeryContext;
    use rump::BigUint;

    fn u(value: u64) -> BigUint {
        BigUint::from_u64(value)
    }

    /// The smallest group the size policy admits with `p = 2q + 1`: `q =
    /// 32771` (the least prime at or above `2^15`) and `p = 65543`, both
    /// prime. `g = 4 = 2^2` is a quadratic residue, so its order divides `q`
    /// and, being not `1`, is `q`. Values are small enough to check by hand
    /// and wide enough (`N = 16`) that a digest is two bytes.
    const P: u64 = 65543;
    const Q: u64 = 32771;
    const G: u64 = 4;

    /// A key pair over a fresh toy group: far below FIPS 186-4's sizes, which
    /// a debug build generates too slowly for most unit tests.
    fn toy_keypair(seed: u8) -> (DsaPublicKey, DsaPrivateKey) {
        let mut drbg = CtrDrbgAes256::new(&[seed; 48]);
        let params = Dsa::generate_toy_params(&mut drbg, 64).expect("a toy size");
        Dsa::generate(&params, &mut drbg)
    }

    /// The reference key: `x = 3`, so `y = 4^3 = 64`.
    fn derive_small_reference_key() -> (DsaPublicKey, DsaPrivateKey) {
        Dsa::from_secret_exponent(&u(P), &u(Q), &u(G), &u(3)).expect("valid DSA key")
    }

    #[test]
    fn derive_small_reference_key_components() {
        let (public, private) = derive_small_reference_key();
        assert_eq!(public.modulus(), &u(P));
        assert_eq!(public.subgroup_order(), &u(Q));
        assert_eq!(public.generator(), &u(G));
        assert_eq!(public.public_component(), &u(64));
        assert_eq!(private.exponent(), &u(3));
        assert_eq!(private.to_public_key(), public);
    }

    /// `k = 5`: `r = 4^5 mod 65543 mod 32771 = 1024`; the digest `0x1234` is
    /// sixteen bits, `N`, so `z = 0x1234 = 4660`, and
    /// `s = 5^-1 (4660 + 3·1024) mod 32771 = 21209`.
    #[test]
    fn exact_small_signature_matches_reference() {
        let (public, private) = derive_small_reference_key();
        let signature = private
            .sign_digest_with_nonce(&[0x12, 0x34], &u(5))
            .expect("valid DSA nonce");
        assert_eq!(signature.r(), &u(1024));
        assert_eq!(signature.s(), &u(21209));
        assert!(public.verify(&[0x12, 0x34], &signature));
        // The leftmost N = 16 bits are kept: a longer digest with the same
        // first two bytes signs and verifies identically.
        let longer = private
            .sign_digest_with_nonce(&[0x12, 0x34, 0xff, 0xff], &u(5))
            .expect("valid DSA nonce");
        assert_eq!(longer, signature);
    }

    /// A random source that plays back a script of two-byte draws and counts
    /// them. Under the 16-bit `q` the nonce sampler asks for exactly two
    /// bytes per draw and accepts any value in `[1, q)`, so each entry is the
    /// nonce of one draw; once the script is used up the last entry repeats.
    struct ScriptedRng {
        script: Vec<u16>,
        draws: usize,
    }

    impl ScriptedRng {
        fn new(script: &[u16]) -> Self {
            Self {
                script: script.to_vec(),
                draws: 0,
            }
        }
    }

    impl crate::Csprng for ScriptedRng {
        fn fill_bytes(&mut self, out: &mut [u8]) {
            assert_eq!(out.len(), 2, "a 16-bit q draws two bytes");
            let value = self.script[self.draws.min(self.script.len() - 1)];
            out.copy_from_slice(&value.to_be_bytes());
            self.draws += 1;
        }
    }

    /// On the reference key (`g = 4`, `x = 3`) the nonce `k = 1` gives `r = 4`
    /// and `x·r = 12`, so the digest `0x7ff7`, whose value is `z = 32759 ≡
    /// −12 (mod q)`, makes `s = z + xr ≡ 0`. FIPS 186-4 §4.6 then calls for a
    /// new `k`: a source that yields that `k` once and then a good one signs
    /// on the second draw, and a source stuck on it is refused with `None`
    /// after exactly `MAX_NONCE_DRAWS` draws.
    #[test]
    fn randomized_signing_retries_a_zeroing_nonce_and_refuses_a_source_stuck_on_it() {
        let (public, private) = derive_small_reference_key();
        let digest = [0x7f, 0xf7];
        assert!(private
            .sign_digest_with_nonce(&digest, &BigUint::one())
            .is_none());
        let good = private
            .sign_digest_with_nonce(&digest, &u(5))
            .expect("k = 5 signs this digest");

        let mut retrying = ScriptedRng::new(&[1, 5]);
        let signature = private
            .sign_digest_with_rng(&digest, &mut retrying)
            .expect("the second draw signs");
        assert_eq!(signature, good);
        assert!(public.verify(&digest, &signature));
        assert_eq!(
            retrying.draws, 2,
            "exactly two draws: the rejected k and the good one"
        );

        let mut stuck = ScriptedRng::new(&[1]);
        assert_eq!(private.sign_digest_with_rng(&digest, &mut stuck), None);
        assert_eq!(stuck.draws, MAX_NONCE_DRAWS);
    }

    /// In the order-2 subgroup `{1, 22}` of `Z_23*` (`q = 2`, `g = 22`) the
    /// only nonce is `k = 1`, and `r = 22 mod 2 = 0`, so no `k` signs. The
    /// size policy refuses the group, so the key is built here directly,
    /// behind the constructors; the deterministic signer stops after
    /// `MAX_NONCE_DRAWS` candidates with `None` rather than searching forever.
    #[test]
    fn deterministic_signing_gives_up_where_every_nonce_is_rejected() {
        assert!(DsaParams::new(u(23), u(2), u(22)).is_none());
        let private = DsaPrivateKey {
            p: u(23),
            q: u(2),
            g: u(22),
            x: u(1),
            y: u(22),
            p_ctx: MontgomeryContext::new(&u(23)).ok(),
            q_ctx: None,
        };
        assert!(private
            .sign_digest_with_nonce(&[0x09], &BigUint::one())
            .is_none());
        assert_eq!(private.sign_digest::<Sha256>(&[0x09]), None);
    }

    #[test]
    fn rejects_invalid_parameters() {
        // g = 5 is a quadratic non-residue modulo 65543: it is outside the
        // order-q subgroup. q = 32769 = 3 · 10923 is composite.
        assert!(Dsa::from_secret_exponent(&u(P), &u(Q), &u(5), &u(3)).is_none());
        assert!(Dsa::from_secret_exponent(&u(P), &u(32769), &u(G), &u(3)).is_none());
        assert!(Dsa::from_secret_exponent(&u(P), &u(Q), &u(G), &BigUint::zero()).is_none());
        assert!(Dsa::from_secret_exponent(&u(P), &u(Q), &u(G), &u(Q)).is_none());
        // A prime-order subgroup below the size policy: q = 11 in Z_23*.
        assert!(Dsa::from_secret_exponent(&u(23), &u(11), &u(4), &u(3)).is_none());
        assert!(DsaParams::new(u(23), u(11), u(4)).is_none());
    }

    #[test]
    fn with_secret_exponent_checks_only_the_exponent_range() {
        let params = DsaParams::new(u(P), u(Q), u(G)).expect("reference group");
        let (public, private) = Dsa::with_secret_exponent(&params, &u(3)).expect("x = 3");
        assert_eq!(public.public_component(), &u(64));
        assert_eq!(private.params(), params);
        assert!(Dsa::with_secret_exponent(&params, &BigUint::zero()).is_none());
        assert!(Dsa::with_secret_exponent(&params, &u(Q)).is_none());
        let (top, _) = Dsa::with_secret_exponent(&params, &u(Q - 1)).expect("x = q − 1");
        // g^(q−1) = g^-1: the inverse of 4 modulo 65543.
        assert_eq!(
            BigUint::mod_mul(top.public_component(), &u(G), &u(P)),
            BigUint::one()
        );
    }

    #[test]
    fn from_public_component_applies_full_public_key_validation() {
        let params = DsaParams::new(u(P), u(Q), u(G)).expect("reference group");
        let public = DsaPublicKey::from_public_component(&params, u(64)).expect("y = 4^3");
        assert_eq!(public, derive_small_reference_key().0);
        // The identity, zero, p, p − 1 (order 2), and two quadratic
        // non-residues (5 and q itself), which lie outside the subgroup.
        for y in [1, 0, P, P - 1, 5, Q] {
            assert!(
                DsaPublicKey::from_public_component(&params, u(y)).is_none(),
                "y = {y}"
            );
        }
    }

    #[test]
    fn sign_and_verify_roundtrip() {
        let (public, private) = toy_keypair(0x31);
        let digest = b"dsa-signature-digest";
        let signature = private.sign_digest::<Sha256>(digest).expect("signature");
        assert!(public.verify(digest, &signature));
        assert!(!public.verify(b"wrong-digest", &signature));
    }

    #[test]
    fn sign_bytes_roundtrip() {
        let (public, private) = toy_keypair(0x44);
        let digest = b"dsa-bytes";
        let signature = private
            .sign_digest_bytes::<Sha256>(digest)
            .expect("signature bytes");
        assert!(public.verify_bytes(digest, &signature));
    }

    #[test]
    fn sign_message_roundtrip() {
        let (public, private) = toy_keypair(0x45);
        let message = b"dsa full message";
        let signature = private
            .sign_message::<Sha256>(message)
            .expect("message signature");
        assert!(public.verify_message::<Sha256>(message, &signature));
    }

    #[test]
    fn tampered_signature_is_rejected() {
        let (public, private) = toy_keypair(0x46);
        let digest = b"dsa-tamper";
        let mut signature = private.sign_digest::<Sha256>(digest).expect("signature");
        signature.s = signature
            .s
            .add(&BigUint::one())
            .rem(public.subgroup_order());
        if signature.s.is_zero() {
            signature.s = BigUint::one();
        }
        assert!(!public.verify(digest, &signature));
    }

    #[test]
    fn cross_key_signature_is_rejected() {
        let (public_a, private_a) = toy_keypair(0x47);
        let (public_b, _) = toy_keypair(0x48);
        let digest = b"dsa-cross";
        let signature = private_a.sign_digest::<Sha256>(digest).expect("signature");
        assert!(public_a.verify(digest, &signature));
        assert!(!public_b.verify(digest, &signature));
    }

    #[test]
    fn sign_digest_with_nonce_rejects_out_of_range_nonce() {
        let (_public, private) = derive_small_reference_key();
        assert!(private
            .sign_digest_with_nonce(&[0x12, 0x34], &BigUint::zero())
            .is_none());
        assert!(private
            .sign_digest_with_nonce(&[0x12, 0x34], private.subgroup_order())
            .is_none());
    }

    #[test]
    fn sign_digest_with_nonce_is_deterministic_for_fixed_nonce() {
        let (_public, private) = derive_small_reference_key();
        let digest = [0x12, 0x34];
        let nonce = u(7);
        let lhs = private
            .sign_digest_with_nonce(&digest, &nonce)
            .expect("first explicit nonce signature");
        let rhs = private
            .sign_digest_with_nonce(&digest, &nonce)
            .expect("second explicit nonce signature");
        assert_eq!(lhs, rhs);
    }

    #[test]
    fn toy_params_refuse_sizes_fips_covers_or_that_cannot_be_built() {
        let mut drbg = CtrDrbgAes256::new(&[0x49; 48]);
        for bits in (0..19).chain([1024, 2048, 3072]) {
            assert!(
                Dsa::generate_toy_params(&mut drbg, bits).is_none(),
                "{bits} bits"
            );
        }
    }

    #[test]
    fn generate_params_refuses_a_hash_shorter_than_n() {
        let mut drbg = CtrDrbgAes256::new(&[0x4c; 48]);
        for size in [FfcParameterSize::L2048N256, FfcParameterSize::L3072N256] {
            assert!(Dsa::generate_params(&mut drbg, size, FfcHash::Sha224).is_none());
            assert!(Dsa::generate_params(&mut drbg, size, FfcHash::Sha512_224).is_none());
        }
    }

    #[test]
    fn seeded_params_round_trip_and_sign_in_their_group() {
        let (p, q, g, seed) = cavp::fips186_4_1024_parts(1);
        let params = DsaParams::with_seed(p.clone(), q.clone(), g.clone(), seed.clone())
            .expect("CAVP parameters validate");
        assert_eq!(params.seed(), Some(&seed));
        assert_eq!(
            DsaParams::from_key_blob(&params.to_key_blob()),
            Some(params.clone())
        );
        let pem = params.to_pem();
        assert!(pem.contains("DSA PARAMETERS"));
        assert_eq!(DsaParams::from_pem(&pem), Some(params.clone()));
        assert_eq!(DsaParams::from_xml(&params.to_xml()), Some(params.clone()));
        // The seedless form parses too, and a tampered counter does not.
        let seedless = DsaParams::from_key_blob(&encode_biguints(&[&p, &q, &g])).expect("3 fields");
        assert_eq!(seedless.seed(), None);
        let mut drbg = CtrDrbgAes256::new(&[0x4d; 48]);
        let (public, private) = Dsa::generate(&params, &mut drbg);
        assert_eq!(private.params(), seedless);
        assert_eq!(public.params(), Some(seedless));
        let signature = private
            .sign_message_with_rng::<Sha256, _>(b"fips 186-4 group", &mut drbg)
            .expect("signature");
        assert!(public.verify_message::<Sha256>(b"fips 186-4 group", &signature));
        let index_2_generator = cavp::fips186_4_1024_parts(2).2;
        assert!(DsaParams::with_seed(p, q, index_2_generator, seed).is_none());
    }

    /// An oversized modulus or subgroup order is refused by the size policy
    /// before any primality test runs: the PEM of a 16385-bit `p` (2^16384 +
    /// 1, which no test ever exponentiates) and of a 513-bit `q` each come
    /// back `None` in well under the time one hardened test at that size
    /// would take, on every parser.
    #[test]
    fn oversized_parameters_are_refused_before_any_arithmetic() {
        let mut wide_p = BigUint::zero();
        wide_p.set_bit(16384);
        wide_p = wide_p.add(&BigUint::one());
        let mut wide_q = BigUint::zero();
        wide_q.set_bit(512);
        wide_q = wide_q.add(&BigUint::one());
        let (p, q, g, _) = cavp::fips186_4_1024_parts(1);
        let oversized = [
            encode_biguints(&[&wide_p, &q, &g]),
            encode_biguints(&[&p, &wide_q, &g]),
        ];
        for blob in &oversized {
            let pem = pem_wrap(DSA_PARAMS_LABEL, blob);
            let elapsed = crate::test_utils::fastest_of_three(|| {
                assert!(DsaParams::from_pem(&pem).is_none());
                assert!(DsaParams::from_key_blob(blob).is_none());
                assert!(DsaParams::from_der(blob).is_none());
            });
            assert!(
                elapsed < crate::test_utils::REFUSAL_BOUND,
                "refusal took {elapsed:?}"
            );
        }
        // The key parsers apply the same policy, structural and hardened alike.
        let public = encode_biguints(&[&wide_p, &q, &g, &g]);
        let private = encode_biguints(&[&wide_p, &q, &g, &u(3)]);
        let elapsed = crate::test_utils::fastest_of_three(|| {
            assert!(DsaPublicKey::from_key_blob(&public).is_none());
            assert!(DsaPrivateKey::from_key_blob(&private).is_none());
        });
        assert!(
            elapsed < crate::test_utils::REFUSAL_BOUND,
            "refusal took {elapsed:?}"
        );
    }

    #[test]
    #[ignore = "FIPS 186-4 generation at 2048 and 3072 bits is slow in debug; run with --release --ignored"]
    fn generated_params_at_every_approved_size_validate_and_sign() {
        let mut drbg = CtrDrbgAes256::new(&[0x4e; 48]);
        for size in FfcParameterSize::ALL {
            let hash = if size.n() <= 224 {
                FfcHash::Sha224
            } else {
                FfcHash::Sha256
            };
            let params =
                Dsa::generate_params(&mut drbg, size, hash).expect("approved size and hash");
            assert_eq!(params.modulus().bits(), size.l());
            assert_eq!(params.subgroup_order().bits(), size.n());
            let seed = params
                .seed()
                .expect("generated parameters carry a seed")
                .clone();
            assert_eq!(seed.index(), 1);
            let validated = DsaParams::with_seed(
                params.modulus().clone(),
                params.subgroup_order().clone(),
                params.generator().clone(),
                seed,
            );
            assert_eq!(validated.as_ref(), Some(&params));
            let (public, private) = Dsa::generate(&params, &mut drbg);
            let signature = private
                .sign_message::<Sha256>(b"approved size")
                .expect("sign");
            assert!(public.verify_message::<Sha256>(b"approved size", &signature));
        }
    }

    #[test]
    fn serialization_roundtrip_preserves_verification() {
        let (public, private) = toy_keypair(0x4A);
        let digest = b"dsa-serialize";
        let signature = private.sign_digest::<Sha256>(digest).expect("signature");
        let public_xml = public.to_xml();
        let public_again = DsaPublicKey::from_xml(&public_xml).expect("public xml");
        assert!(public_again.verify(digest, &signature));
    }

    #[test]
    fn digest_to_scalar_truncates_by_digest_width() {
        let q = BigUint::from_u64(257); // 9-bit subgroup order
        let digest = [0x00u8, 0xff];
        let value = super::digest_to_scalar(&digest, &q);
        assert_eq!(value, BigUint::one());
    }

    #[test]
    fn serialization_roundtrip() {
        let (public, private) = toy_keypair(0x55);

        let public_blob = public.to_key_blob();
        let public_pem = public.to_pem();
        let public_xml = public.to_xml();
        let private_blob = private.to_key_blob();
        let private_pem = private.to_pem();
        let private_xml = private.to_xml();

        let public_from_blob = DsaPublicKey::from_key_blob(&public_blob).expect("public binary");
        let public_from_pem = DsaPublicKey::from_pem(&public_pem).expect("public pem");
        let public_from_xml = DsaPublicKey::from_xml(&public_xml).expect("public xml");
        let private_from_blob =
            DsaPrivateKey::from_key_blob(&private_blob).expect("private binary");
        let private_from_pem = DsaPrivateKey::from_pem(&private_pem).expect("private pem");
        let private_from_xml = DsaPrivateKey::from_xml(&private_xml).expect("private xml");

        assert_eq!(public_from_blob, public);
        assert_eq!(public_from_pem, public);
        assert_eq!(public_from_xml, public);
        assert_eq!(private_from_blob, private);
        assert_eq!(private_from_pem, private);
        assert_eq!(private_from_xml, private);
    }

    #[test]
    fn verify_rejects_r_and_s_outside_subgroup_range() {
        // FIPS 186-4 §4.7 step 1: reject unless 0 < r < q and 0 < s < q.
        let (public, private) = derive_small_reference_key();
        let digest = [0x12, 0x34];
        let good = private
            .sign_digest_with_nonce(&digest, &u(5))
            .expect("valid nonce");
        assert!(public.verify(&digest, &good));
        let q = public.subgroup_order().clone();
        for (r, s) in [
            (BigUint::zero(), good.s.clone()),
            (good.r.clone(), BigUint::zero()),
            (q.clone(), good.s.clone()),
            (good.r.clone(), q.clone()),
            (q.add(&good.r), good.s.clone()),
            (good.r.clone(), q.add(&good.s)),
        ] {
            let bad = DsaSignature { r, s };
            assert!(!public.verify(&digest, &bad), "{bad:?}");
        }
        // The DER decoder already refuses zero components.
        let zero_r = encode_biguints(&[&BigUint::zero(), &good.s]);
        assert!(DsaSignature::from_der(&zero_r).is_none());
        assert!(!public.verify_bytes(&digest, &zero_r));
    }

    #[test]
    fn public_key_parse_rejects_tampered_fields() {
        // p = 65543, q = 32771, g = 4, y = 4^3 = 64: valid.
        assert!(
            DsaPublicKey::from_key_blob(&encode_biguints(&[&u(P), &u(Q), &u(G), &u(64)])).is_some()
        );
        // y outside the subgroup: 1 (identity), 0, p, p - 1 (order 2), and
        // the quadratic non-residues 5 and q.
        for y in [1u64, 0, P, P - 1, 5, Q] {
            let blob = encode_biguints(&[&u(P), &u(Q), &u(G), &u(y)]);
            assert!(DsaPublicKey::from_key_blob(&blob).is_none(), "y = {y}");
        }
        // Composite p (65545 = 5 · 13109), composite q (32769 = 3 · 10923),
        // a prime q not dividing p - 1 (32779), q >= p, g outside the
        // subgroup, g = 1, a subgroup order below the size policy (q = 11
        // in Z_23*), and the wrong field count.
        for fields in [
            [65545u64, Q, G, 64],
            [P, 32769, G, 64],
            [P, 32779, G, 64],
            [P, P, G, 64],
            [P, Q, 5, 64],
            [P, Q, 1, 64],
            [23, 11, 4, 18],
        ] {
            let values: Vec<BigUint> = fields.iter().map(|&v| u(v)).collect();
            let refs: Vec<&BigUint> = values.iter().collect();
            assert!(
                DsaPublicKey::from_key_blob(&encode_biguints(&refs)).is_none(),
                "{fields:?}"
            );
        }
        assert!(DsaPublicKey::from_key_blob(&encode_biguints(&[&u(P), &u(Q), &u(G)])).is_none());
    }

    #[test]
    fn private_key_parse_rejects_tampered_fields() {
        let ok = DsaPrivateKey::from_key_blob(&encode_biguints(&[&u(P), &u(Q), &u(G), &u(3)]))
            .expect("valid private key");
        assert_eq!(ok.to_public_key().public_component(), &u(64));
        for fields in [
            [P, Q, G, 0],
            [P, Q, G, Q],
            [65545, Q, G, 3],
            [P, 32769, G, 3],
            [P, Q, 5, 3],
            [23, 11, 4, 3],
        ] {
            let values: Vec<BigUint> = fields.iter().map(|&v| u(v)).collect();
            let refs: Vec<&BigUint> = values.iter().collect();
            assert!(
                DsaPrivateKey::from_key_blob(&encode_biguints(&refs)).is_none(),
                "{fields:?}"
            );
        }
    }

    #[test]
    fn signature_der_matches_key_blob() {
        let signature = DsaSignature {
            r: BigUint::from_u64(0x81),
            s: BigUint::from_u64(9),
        };
        let der = signature.to_der();
        assert_eq!(der, [0x30, 0x07, 0x02, 0x02, 0x00, 0x81, 0x02, 0x01, 0x09]);
        assert_eq!(signature.to_key_blob(), der);
        assert_eq!(DsaSignature::from_der(&der), Some(signature));
        // Non-minimal INTEGER for s is not DER.
        let ber = [0x30, 0x08, 0x02, 0x02, 0x00, 0x81, 0x02, 0x02, 0x00, 0x09];
        assert!(DsaSignature::from_der(&ber).is_none());
    }

    #[test]
    fn signature_binary_roundtrip() {
        let signature = DsaSignature {
            r: BigUint::from_u64(1),
            s: BigUint::from_u64(9),
        };
        let blob = signature.to_key_blob();
        let parsed = DsaSignature::from_key_blob(&blob).expect("signature");
        assert_eq!(parsed, signature);
    }

    #[test]
    fn verify_message_matches_explicit_digest() {
        let (public, private) = toy_keypair(0x4B);
        let message = b"dsa-digest";
        let digest = Sha384::digest(message);
        let signature = private.sign_digest::<Sha384>(&digest).expect("signature");
        assert!(public.verify_message::<Sha384>(message, &signature));
    }

    /// RFC 6979 §3.2 step h.3: a candidate that gives `r = 0` or `s = 0` is
    /// rejected and the next one taken. Both cases, found by an independent
    /// HMAC-SHA-256 computation of the §3.2 stream over each group:
    ///
    /// - `r = 0`: in `Z_1179757*` (`p = 36q + 1`, `q = 32771`) the subgroup
    ///   element `557107 = 17q` is a multiple of `q`; with `g = 2^36 mod p =
    ///   991000`, `x = 3` and the digest `0x13a4`, the first candidate
    ///   `k = 14779` lands on it.
    /// - `s = 0`: on the reference group with `x = 7` and the digest
    ///   `0x14ec`, the first candidate `k = 29681` gives `r = 8598` and
    ///   `z + xr ≡ 0 (mod q)`.
    #[test]
    fn deterministic_signing_retries_zero_r_and_s() {
        for (p, g, x, digest, rejected, r, s) in [
            (1_179_757, 991_000, 3, [0x13, 0xa4], 14779, 22939, 6802), // r = 0 first
            (P, G, 7, [0x14, 0xec], 29681, 11359, 28970),              // s = 0 first
        ] {
            let (public, private) =
                Dsa::from_secret_exponent(&u(p), &u(Q), &u(g), &u(x)).expect("valid toy domain");
            assert!(private
                .sign_digest_with_nonce(&digest, &u(rejected))
                .is_none());
            let signature = private.sign_digest::<Sha256>(&digest).expect("retry");
            assert_eq!(signature.r(), &u(r));
            assert_eq!(signature.s(), &u(s));
            assert!(public.verify(&digest, &signature));
            assert_eq!(private.sign_digest::<Sha256>(&digest), Some(signature));
        }
    }

    #[test]
    fn rfc6979_dsa_1024_sha256_sample_vector() {
        // RFC 6979, Appendix A.2.1 (DSA, 1024 bits), SHA-256, message "sample".
        let p = BigUint::from_be_bytes(&decode_hex(
            "86F5CA03DCFEB225063FF830A0C769B9DD9D6153AD91D7CE27F787C43278B447\
             E6533B86B18BED6E8A48B784A14C252C5BE0DBF60B86D6385BD2F12FB763ED88\
             73ABFD3F5BA2E0A8C0A59082EAC056935E529DAF7C610467899C77ADEDFC846C\
             881870B7B19B2B58F9BE0521A17002E3BDD6B86685EE90B3D9A1B02B782B1779",
        ));
        let q = BigUint::from_be_bytes(&decode_hex("996F967F6C8E388D9E28D01E205FBA957A5698B1"));
        let g = BigUint::from_be_bytes(&decode_hex(
            "07B0F92546150B62514BB771E2A0C0CE387F03BDA6C56B505209FF25FD3C133D\
             89BBCD97E904E09114D9A7DEFDEADFC9078EA544D2E401AEECC40BB9FBBF78FD\
             87995A10A1C27CB7789B594BA7EFB5C4326A9FE59A070E136DB77175464ADCA4\
             17BE5DCE2F40D10A46A3A3943F26AB7FD9C0398FF8C76EE0A56826A8A88F1DBD",
        ));
        let x = BigUint::from_be_bytes(&decode_hex("411602CB19A6CCC34494D79D98EF1E7ED5AF25F7"));

        let (public, private) =
            Dsa::from_secret_exponent(&p, &q, &g, &x).expect("RFC key must be valid");
        let message = b"sample";
        let digest = Sha256::digest(message);

        let expected_k =
            BigUint::from_be_bytes(&decode_hex("519BA0546D0C39202A7D34D7DFA5E760B318BCFB"));
        let derived_k = super::NonceGenerator::<Sha256>::new(&q, &x, &digest)
            .expect("RFC nonce must derive")
            .next();
        assert_eq!(derived_k, expected_k, "RFC 6979 nonce mismatch");

        let signature = private.sign_message::<Sha256>(message).expect("sign");
        let expected_r =
            BigUint::from_be_bytes(&decode_hex("81F2F5850BE5BC123C43F71A3033E9384611C545"));
        let expected_s =
            BigUint::from_be_bytes(&decode_hex("4CDD914B65EB6C66A8AAAD27299BEE6B035F5E89"));
        assert_eq!(signature.r(), &expected_r);
        assert_eq!(signature.s(), &expected_s);
        assert!(public.verify_message::<Sha256>(message, &signature));
    }
}
