//! Edwards-curve Digital Signature Algorithm style signatures.
//!
//! This module builds a Schnorr/EdDSA-style signature layer on top of the
//! existing twisted Edwards arithmetic in [`ec_edwards`].  The signing
//! equation follows the standard Edwards pattern:
//!
//! - choose a nonce scalar `k`
//! - compute `R = k·G`
//! - hash `R || A || M` to a scalar challenge `e`
//! - return `S = k + e·d mod n`
//!
//! Verification checks `S·G = R + e·A`.
//!
//! This is intentionally *not* a byte-for-byte RFC 8032 Ed25519 clone: the
//! key type stores the scalar directly instead of the RFC's hashed/clamped
//! secret-key seed format, and the challenge reads the digest as a
//! big-endian integer, the convention of the crate's other hash-to-scalar
//! maps (FIPS 186's `bits2int`, as DSA and ECDSA use it), where RFC 8032
//! §5.1.7 reads SHA-512 little-endian; [`crate::public_key::ed25519`] does
//! that.  The point arithmetic and point encoding still use the Edwards
//! machinery in [`ec_edwards`], so the module is suitable for the crate's
//! "pure Rust, explicit arithmetic" design.
//!
//! # Verification and the order of `R`
//!
//! The public key `A` is checked into the prime-order subgroup on every
//! import path ([`TwistedEdwardsCurve::is_valid_public_point`]). The nonce
//! point `R` of a signature is checked only to be a canonical point of the
//! curve other than the neutral element, which is what the complete
//! addition law needs to be meaningful; its order is left to the equation.
//! `S·G` and `e·A` both lie in the subgroup generated by `G`, so
//! `S·G = R + e·A` forces `R = S·G − e·A` into it: an `R` with a small-order
//! component fails the equation by itself. This is the uncofactored equation
//! RFC 8032 §5.1.7 calls "sufficient, but not required"; the crate's RFC 8032
//! module checks the cofactored one and accepts what that accepts, while this
//! layer, whose keys are always of order `n`, checks the stronger one and
//! spends no `[n]R` ladder on an attacker's `R` before doing so.
//!
//! Keys imported with explicit curve parameters (key blob, PEM, XML) are
//! validated by [`TwistedEdwardsCurve::from_explicit`] before any scalar
//! multiplication, so a hostile encoding cannot buy a long computation.
//!
//! [`ec_edwards`]: crate::public_key::ec_edwards

use core::fmt;

use crate::hash::Digest;
use crate::public_key::ec_edwards::{EdwardsMulTable, EdwardsPoint, TwistedEdwardsCurve};
use crate::public_key::io::{decode_biguints, encode_biguints};
use crate::Csprng;
use rump::BigUint;

const EDDSA_PUBLIC_LABEL: &str = "CRYPTOGRAPHY EDDSA PUBLIC KEY";
const EDDSA_PRIVATE_LABEL: &str = "CRYPTOGRAPHY EDDSA PRIVATE KEY";

/// Public key for the Edwards-curve signature layer.
#[derive(Clone, Debug)]
pub struct EdDsaPublicKey {
    /// Edwards curve parameters.
    curve: TwistedEdwardsCurve,
    /// Public point `A = d·G`.
    a_point: EdwardsPoint,
    /// Cached precompute table for repeated `k·A` verification work.
    a_table: EdwardsMulTable,
}

/// Private key for the Edwards-curve signature layer.
#[derive(Clone)]
pub struct EdDsaPrivateKey {
    /// Edwards curve parameters.
    curve: TwistedEdwardsCurve,
    /// Secret scalar `d ∈ [1, n)`.
    d: BigUint,
    /// Cached public point `A = d·G`.
    ///
    /// Signing hashes `R || A || M`, so caching `A` avoids a full scalar
    /// multiplication on every signature.
    a_point: EdwardsPoint,
}

/// Signature pair `(R, S)`.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EdDsaSignature {
    /// Nonce point `R = k·G`.
    r_point: EdwardsPoint,
    /// Response scalar `S = k + e·d mod n`.
    s: BigUint,
}

/// Namespace wrapper for the Edwards-curve signature construction.
pub struct EdDsa;

impl PartialEq for EdDsaPublicKey {
    fn eq(&self, other: &Self) -> bool {
        self.curve.same_curve(&other.curve) && self.a_point == other.a_point
    }
}

impl Eq for EdDsaPublicKey {}

impl PartialEq for EdDsaPrivateKey {
    /// Compares the (public) curve parameters, then the secret scalars in
    /// constant time over fixed-width encodings, which are wiped afterwards.
    fn eq(&self, other: &Self) -> bool {
        if !self.curve.same_curve(&other.curve) {
            return false;
        }
        // Both scalars lie in [1, n), so the width of `n` fits either.
        let width = self.curve.n.bits().div_ceil(8);
        let mut lhs = self.d.to_be_bytes_padded(width);
        let mut rhs = other.d.to_be_bytes_padded(width);
        let equal = crate::ct::constant_time_eq_mask(&lhs, &rhs) == u8::MAX;
        crate::ct::zeroize_slice(lhs.as_mut_slice());
        crate::ct::zeroize_slice(rhs.as_mut_slice());
        equal
    }
}

impl Eq for EdDsaPrivateKey {}

impl EdDsaPublicKey {
    /// Return the curve parameters.
    #[must_use]
    pub fn curve(&self) -> &TwistedEdwardsCurve {
        &self.curve
    }

    /// Return the public point `A = d·G`.
    #[must_use]
    pub fn public_point(&self) -> &EdwardsPoint {
        &self.a_point
    }

    /// Encode just the public point using the curve's compressed Edwards form.
    #[must_use]
    pub fn to_wire_bytes(&self) -> Vec<u8> {
        self.curve.encode_point(&self.a_point)
    }

    /// Rebuild a public key from a compressed Edwards point plus explicit curve parameters.
    #[must_use]
    pub fn from_wire_bytes(curve: TwistedEdwardsCurve, bytes: &[u8]) -> Option<Self> {
        let a_point = curve.decode_point(bytes)?;
        if !curve.is_valid_public_point(&a_point) {
            return None;
        }
        let a_table = curve.precompute_mul_table(&a_point);
        Some(Self {
            curve,
            a_point,
            a_table,
        })
    }

    /// Verify a signature over a raw message byte string.
    ///
    /// `S` must lie in `[1, n)` and `R` must be a canonical, non-neutral
    /// point of the curve; `R`'s order is decided by the equation itself
    /// (see the module documentation), so no `[n]R` ladder is spent on it.
    #[must_use]
    pub fn verify_message<H: Digest>(&self, message: &[u8], signature: &EdDsaSignature) -> bool {
        if signature.s.is_zero() || signature.s >= self.curve.n {
            return false;
        }
        if !is_usable_nonce_point(&self.curve, &signature.r_point) {
            return false;
        }

        let challenge =
            challenge_scalar::<H>(&self.curve, &signature.r_point, &self.a_point, message);

        let lhs = self.curve.scalar_mul_base(&signature.s);
        let rhs = self.curve.add(
            &signature.r_point,
            &self.curve.scalar_mul_cached(&self.a_table, &challenge),
        );
        lhs == rhs
    }

    /// Verify a byte-encoded signature produced by [`EdDsaPrivateKey::sign_message_bytes`].
    #[must_use]
    pub fn verify_message_bytes<H: Digest>(&self, message: &[u8], signature: &[u8]) -> bool {
        let Some(signature) = EdDsaSignature::from_key_blob(signature, &self.curve) else {
            return false;
        };
        self.verify_message::<H>(message, &signature)
    }

    /// Schema fields for the crate-defined serialization formats.
    fn serial_fields(&self) -> Vec<BigUint> {
        vec![
            self.curve.p.clone(),
            self.curve.a.clone(),
            self.curve.d.clone(),
            self.curve.n.clone(),
            self.curve.gx.clone(),
            self.curve.gy.clone(),
            self.a_point.x.clone(),
            self.a_point.y.clone(),
        ]
    }

    /// Validate schema fields and rebuild the key with its derived state.
    fn from_serial_fields(fields: Vec<BigUint>) -> Option<Self> {
        let mut fields = fields.into_iter();
        let p = fields.next()?;
        let a = fields.next()?;
        let d = fields.next()?;
        let n = fields.next()?;
        let gx = fields.next()?;
        let gy = fields.next()?;
        let ax = fields.next()?;
        let ay = fields.next()?;
        let curve = TwistedEdwardsCurve::from_explicit(p, a, d, n, gx, gy)?;
        let a_point = EdwardsPoint::new(ax, ay);
        if !curve.is_valid_public_point(&a_point) {
            return None;
        }
        let a_table = curve.precompute_mul_table(&a_point);
        Some(Self {
            curve,
            a_point,
            a_table,
        })
    }
}

crate::public_key::io::impl_xml_serialization!(
    EdDsaPublicKey,
    "EdDsaPublicKey",
    ["p", "a", "d", "n", "gx", "gy", "ax", "ay"]
);
crate::public_key::io::impl_blob_pem_serialization!(
    EdDsaPublicKey,
    EDDSA_PUBLIC_LABEL,
    ["p", "a", "d", "n", "gx", "gy", "ax", "ay"]
);

impl EdDsaPrivateKey {
    /// Return the curve parameters.
    #[must_use]
    pub fn curve(&self) -> &TwistedEdwardsCurve {
        &self.curve
    }

    /// Return the private scalar `d ∈ [1, n)`.
    #[must_use]
    pub fn private_scalar(&self) -> &BigUint {
        &self.d
    }

    /// Return the cached public point `A = d·G`.
    #[must_use]
    pub fn public_point(&self) -> &EdwardsPoint {
        &self.a_point
    }

    /// Derive the matching public key `A = d·G`.
    #[must_use]
    pub fn to_public_key(&self) -> EdDsaPublicKey {
        EdDsaPublicKey {
            curve: self.curve.clone(),
            a_point: self.a_point.clone(),
            a_table: self.curve.precompute_mul_table(&self.a_point),
        }
    }

    /// Sign with an explicit nonce scalar `k`.
    ///
    /// Reusing the same nonce with the same private key leaks the secret
    /// scalar from two signatures, so this entry point is for deterministic
    /// tests and fixed vectors only.
    #[must_use]
    pub fn sign_message_with_nonce<H: Digest>(
        &self,
        message: &[u8],
        nonce: &BigUint,
    ) -> Option<EdDsaSignature> {
        if nonce.is_zero() || nonce >= &self.curve.n {
            return None;
        }

        let r_point = self.curve.scalar_mul_base(nonce);
        if r_point.is_neutral() {
            return None;
        }
        let challenge = challenge_scalar::<H>(&self.curve, &r_point, &self.a_point, message);
        let ed = self.curve.scalar_ctx().mul(&challenge, &self.d);
        let s = nonce.add(&ed).rem(&self.curve.n);
        Some(EdDsaSignature { r_point, s })
    }

    /// Sign using a fresh random nonce.
    #[must_use]
    pub fn sign_message<H: Digest, R: Csprng>(
        &self,
        message: &[u8],
        rng: &mut R,
    ) -> Option<EdDsaSignature> {
        loop {
            let nonce = self.curve.random_scalar(rng);
            if let Some(signature) = self.sign_message_with_nonce::<H>(message, &nonce) {
                return Some(signature);
            }
        }
    }

    /// Sign and serialize in one step.
    #[must_use]
    pub fn sign_message_bytes<H: Digest, R: Csprng>(
        &self,
        message: &[u8],
        rng: &mut R,
    ) -> Option<Vec<u8>> {
        let signature = self.sign_message::<H, R>(message, rng)?;
        Some(signature.to_key_blob())
    }

    /// Schema fields for the crate-defined serialization formats.
    fn serial_fields(&self) -> Vec<BigUint> {
        vec![
            self.curve.p.clone(),
            self.curve.a.clone(),
            self.curve.d.clone(),
            self.curve.n.clone(),
            self.curve.gx.clone(),
            self.curve.gy.clone(),
            self.d.clone(),
        ]
    }

    /// Validate schema fields and rebuild the key with its derived state.
    fn from_serial_fields(fields: Vec<BigUint>) -> Option<Self> {
        let mut fields = fields.into_iter();
        let p = fields.next()?;
        let a = fields.next()?;
        let d_curve = fields.next()?;
        let n = fields.next()?;
        let gx = fields.next()?;
        let gy = fields.next()?;
        let d = fields.next()?;
        let curve = TwistedEdwardsCurve::from_explicit(p, a, d_curve, n, gx, gy)?;
        if d.is_zero() || d >= curve.n {
            return None;
        }
        let a_point = curve.scalar_mul_base(&d);
        Some(Self { curve, d, a_point })
    }
}

crate::public_key::io::impl_xml_serialization!(
    EdDsaPrivateKey,
    "EdDsaPrivateKey",
    ["p", "a", "d", "n", "gx", "gy", "private"]
);
crate::public_key::io::impl_blob_pem_serialization!(
    EdDsaPrivateKey,
    EDDSA_PRIVATE_LABEL,
    ["p", "a", "d", "n", "gx", "gy", "private"]
);

impl fmt::Debug for EdDsaPrivateKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("EdDsaPrivateKey(<redacted>)")
    }
}

impl EdDsaSignature {
    /// Return the nonce point `R`.
    #[must_use]
    pub fn nonce_point(&self) -> &EdwardsPoint {
        &self.r_point
    }

    /// Return the response scalar `S`.
    #[must_use]
    pub fn response(&self) -> &BigUint {
        &self.s
    }

    /// Encode the signature in the crate-defined binary format.
    ///
    /// Field layout: `[Rx, Ry, S]`.
    #[must_use]
    pub fn to_key_blob(&self) -> Vec<u8> {
        encode_biguints(&[&self.r_point.x, &self.r_point.y, &self.s])
    }

    /// Decode a signature from the crate-defined binary format.
    #[must_use]
    pub fn from_key_blob(blob: &[u8], curve: &TwistedEdwardsCurve) -> Option<Self> {
        let mut fields = decode_biguints(blob)?.into_iter();
        let rx = fields.next()?;
        let ry = fields.next()?;
        let s = fields.next()?;
        if fields.next().is_some() || s.is_zero() || s >= curve.n {
            return None;
        }
        // `R` must be a canonical point of the curve (coordinates below `p`,
        // on the curve) and not the neutral element, which the signer never
        // produces; its order is left to the verification equation.
        let r_point = EdwardsPoint::new(rx, ry);
        if !is_usable_nonce_point(curve, &r_point) {
            return None;
        }
        Some(Self { r_point, s })
    }
}

impl EdDsa {
    /// Generate a random key pair `(public, private)` for the chosen curve.
    #[must_use]
    pub fn generate<R: Csprng>(
        curve: TwistedEdwardsCurve,
        rng: &mut R,
    ) -> (EdDsaPublicKey, EdDsaPrivateKey) {
        let (d, a_point) = curve.generate_keypair(rng);
        let public = EdDsaPublicKey {
            curve: curve.clone(),
            a_point: a_point.clone(),
            a_table: curve.precompute_mul_table(&a_point),
        };
        let private = EdDsaPrivateKey { curve, d, a_point };
        (public, private)
    }

    /// Derive a key pair from an explicit secret scalar.
    #[must_use]
    pub fn from_secret_scalar(
        curve: TwistedEdwardsCurve,
        secret: &BigUint,
    ) -> Option<(EdDsaPublicKey, EdDsaPrivateKey)> {
        if secret.is_zero() || secret >= &curve.n {
            return None;
        }
        let a_point = curve.scalar_mul_base(secret);
        if !curve.is_valid_public_point(&a_point) {
            return None;
        }
        Some((
            EdDsaPublicKey {
                curve: curve.clone(),
                a_point: a_point.clone(),
                a_table: curve.precompute_mul_table(&a_point),
            },
            EdDsaPrivateKey {
                curve,
                d: secret.clone(),
                a_point,
            },
        ))
    }
}

/// `true` if `r` can be the nonce point of a signature: a canonical point of
/// the curve other than the neutral element `(0, 1)`, whether flagged as
/// neutral or spelled out as coordinates. Its order is left to the
/// verification equation (see the module documentation).
fn is_usable_nonce_point(curve: &TwistedEdwardsCurve, r: &EdwardsPoint) -> bool {
    let spelled_neutral = r.x.is_zero() && r.y.is_one();
    !r.is_neutral() && !spelled_neutral && curve.is_canonical_point(r)
}

/// Compute the EdDSA-style challenge scalar `e = H(encode(R) || encode(A) || M) mod n`.
///
/// The digest is read as a big-endian integer, the crate's convention for
/// hash-to-scalar maps outside RFC 8032 (FIPS 186's `bits2int`, as DSA and
/// ECDSA use it). RFC 8032 §5.1.7 reads SHA-512 little-endian; that is the
/// Ed25519 module's business, not this generic layer's.
fn challenge_scalar<H: Digest>(
    curve: &TwistedEdwardsCurve,
    r_point: &EdwardsPoint,
    a_point: &EdwardsPoint,
    message: &[u8],
) -> BigUint {
    let mut transcript = curve.encode_point(r_point);
    transcript.extend_from_slice(&curve.encode_point(a_point));
    transcript.extend_from_slice(message);
    BigUint::from_be_bytes(&H::digest(&transcript)).rem(&curve.n)
}

#[cfg(test)]
mod tests {
    use super::{EdDsa, EdDsaPrivateKey, EdDsaPublicKey, EdDsaSignature};
    use crate::public_key::ec_edwards::ed25519;
    use crate::public_key::io::{encode_biguints, xml_wrap};
    use crate::{CtrDrbgAes256, Sha512};
    use rump::BigUint;

    fn rng() -> CtrDrbgAes256 {
        CtrDrbgAes256::new(&[0x5a; 48])
    }

    #[test]
    fn roundtrip_sign_verify_ed25519() {
        let curve = ed25519();
        let (public, private) = EdDsa::generate(curve, &mut rng());
        let sig = private
            .sign_message::<Sha512, _>(b"edwards signature", &mut rng())
            .expect("sign");
        assert!(public.verify_message::<Sha512>(b"edwards signature", &sig));
        assert!(!public.verify_message::<Sha512>(b"wrong", &sig));
    }

    #[test]
    fn sign_with_explicit_nonce_roundtrip() {
        let curve = ed25519();
        let secret = BigUint::from_u64(7);
        let nonce = BigUint::from_u64(11);
        let (public, private) = EdDsa::from_secret_scalar(curve, &secret).expect("explicit secret");
        let sig = private
            .sign_message_with_nonce::<Sha512>(b"abc", &nonce)
            .expect("explicit nonce");
        assert!(public.verify_message::<Sha512>(b"abc", &sig));
    }

    #[test]
    fn sign_message_with_nonce_is_repeatable() {
        let curve = ed25519();
        let secret = BigUint::from_u64(7);
        let nonce = BigUint::from_u64(11);
        let (_public, private) =
            EdDsa::from_secret_scalar(curve, &secret).expect("explicit secret");
        let lhs = private
            .sign_message_with_nonce::<Sha512>(b"abc", &nonce)
            .expect("first signature");
        let rhs = private
            .sign_message_with_nonce::<Sha512>(b"abc", &nonce)
            .expect("second signature");
        assert_eq!(lhs, rhs);
    }

    #[test]
    fn tampered_signature_is_rejected() {
        let curve = ed25519();
        let (public, private) = EdDsa::generate(curve, &mut rng());
        let mut sig = private
            .sign_message::<Sha512, _>(b"tamper", &mut rng())
            .expect("sign");
        sig.s = sig.s.add(&BigUint::one()).rem(&public.curve().n);
        if sig.s.is_zero() {
            sig.s = BigUint::one();
        }
        assert!(!public.verify_message::<Sha512>(b"tamper", &sig));
    }

    #[test]
    fn key_serialization_roundtrip() {
        let curve = ed25519();
        let (public, private) = EdDsa::generate(curve, &mut rng());

        let public_bin = public.to_key_blob();
        let public_pem = public.to_pem();
        let public_xml = public.to_xml();
        assert_eq!(
            EdDsaPublicKey::from_key_blob(&public_bin).expect("public binary"),
            public
        );
        assert_eq!(
            EdDsaPublicKey::from_pem(&public_pem).expect("public pem"),
            public
        );
        assert_eq!(
            EdDsaPublicKey::from_xml(&public_xml).expect("public xml"),
            public
        );

        let private_bin = private.to_key_blob();
        let private_pem = private.to_pem();
        let private_xml = private.to_xml();
        let private_round = EdDsaPrivateKey::from_key_blob(&private_bin).expect("private binary");
        assert_eq!(private_round, private);
        assert_eq!(private_round.to_public_key(), public);
        assert_eq!(
            EdDsaPrivateKey::from_pem(&private_pem).expect("private pem"),
            private
        );
        assert_eq!(
            EdDsaPrivateKey::from_xml(&private_xml).expect("private xml"),
            private
        );
    }

    #[test]
    fn public_bytes_roundtrip() {
        let curve = ed25519();
        let (public, _) = EdDsa::generate(curve.clone(), &mut rng());
        let bytes = public.to_wire_bytes();
        let round = EdDsaPublicKey::from_wire_bytes(curve, &bytes).expect("public bytes");
        assert_eq!(round, public);
    }

    #[test]
    fn signature_binary_roundtrip() {
        let curve = ed25519();
        let (public, private) = EdDsa::generate(curve, &mut rng());
        let sig = private
            .sign_message::<Sha512, _>(b"serialize", &mut rng())
            .expect("sign");
        let blob = sig.to_key_blob();
        let decoded = EdDsaSignature::from_key_blob(&blob, public.curve()).expect("decode sig");
        assert_eq!(decoded, sig);
        assert!(public.verify_message::<Sha512>(b"serialize", &decoded));
    }

    #[test]
    fn signature_binary_rejects_out_of_range_s() {
        let curve = ed25519();
        let base = curve.base_point();
        let blob = encode_biguints(&[&base.x, &base.y, &curve.n]);
        assert!(EdDsaSignature::from_key_blob(&blob, &curve).is_none());
    }

    /// The public-key schema fields with `p` added to field `index` (6 = `ax`,
    /// 7 = `ay`): the same point modulo `p`, encoded non-canonically.
    fn public_fields_offset_by_p(public: &EdDsaPublicKey, index: usize) -> Vec<BigUint> {
        let mut fields = public.serial_fields();
        fields[index] = fields[index].add(&public.curve.p);
        fields
    }

    fn public_blob(fields: &[BigUint]) -> Vec<u8> {
        let refs: Vec<&BigUint> = fields.iter().collect();
        encode_biguints(&refs)
    }

    fn public_xml(fields: &[BigUint]) -> String {
        let names = ["p", "a", "d", "n", "gx", "gy", "ax", "ay"];
        let pairs: Vec<(&str, &BigUint)> = names.iter().copied().zip(fields.iter()).collect();
        xml_wrap("EdDsaPublicKey", &pairs)
    }

    #[test]
    fn public_blob_rejects_non_canonical_coordinates() {
        let (public, _) = EdDsa::generate(ed25519(), &mut rng());
        assert!(EdDsaPublicKey::from_key_blob(&public_blob(&public.serial_fields())).is_some());
        for index in [6, 7] {
            let blob = public_blob(&public_fields_offset_by_p(&public, index));
            assert!(
                EdDsaPublicKey::from_key_blob(&blob).is_none(),
                "blob decode accepted field {index} + p"
            );
        }
    }

    #[test]
    fn public_xml_rejects_non_canonical_coordinates() {
        let (public, _) = EdDsa::generate(ed25519(), &mut rng());
        assert!(EdDsaPublicKey::from_xml(&public_xml(&public.serial_fields())).is_some());
        for index in [6, 7] {
            let xml = public_xml(&public_fields_offset_by_p(&public, index));
            assert!(
                EdDsaPublicKey::from_xml(&xml).is_none(),
                "XML decode accepted field {index} + p"
            );
        }
    }

    #[test]
    fn signature_binary_rejects_non_canonical_r() {
        let curve = ed25519();
        let (_, private) = EdDsa::generate(curve.clone(), &mut rng());
        let sig = private
            .sign_message::<Sha512, _>(b"canonical R", &mut rng())
            .expect("sign");
        let (rx, ry) = (&sig.r_point.x, &sig.r_point.y);
        let canonical = encode_biguints(&[rx, ry, &sig.s]);
        assert!(EdDsaSignature::from_key_blob(&canonical, &curve).is_some());
        let rx_plus_p = rx.add(&curve.p);
        let ry_plus_p = ry.add(&curve.p);
        for blob in [
            encode_biguints(&[&rx_plus_p, ry, &sig.s]),
            encode_biguints(&[rx, &ry_plus_p, &sig.s]),
        ] {
            assert!(EdDsaSignature::from_key_blob(&blob, &curve).is_none());
        }
    }

    /// A public key whose XML carries Ed25519's parameters but an `n` of
    /// 400 000 bits (`2^400000 + 1`, odd). `from_explicit` refuses it at the
    /// size check, before any primality test, Montgomery context or ladder,
    /// so the refusal costs little more than parsing the 100 KB of hex.
    #[test]
    fn public_key_import_refuses_a_400000_bit_order_quickly() {
        let (public, _) = EdDsa::generate(ed25519(), &mut rng());
        let mut fields = public.serial_fields();
        let mut huge_n = BigUint::one();
        huge_n.shl_bits(400_000);
        fields[3] = huge_n.add(&BigUint::one());
        let xml = public_xml(&fields);
        assert!(xml.len() > 100_000);
        let start = std::time::Instant::now();
        assert!(EdDsaPublicKey::from_xml(&xml).is_none());
        let elapsed = start.elapsed();
        assert!(
            elapsed < std::time::Duration::from_millis(50),
            "refusal took {elapsed:?}"
        );
    }

    /// Ed25519's parameters with the order `3n`: `[3n]G` is neutral and
    /// every other check passes, so it is the primality test that refuses
    /// the key, on both the blob and the XML path and for both key types.
    #[test]
    fn key_import_refuses_a_composite_order() {
        let (public, private) = EdDsa::generate(ed25519(), &mut rng());
        let three_n = public.curve.n.mul(&BigUint::from_u64(3));

        let mut fields = public.serial_fields();
        fields[3] = three_n.clone();
        assert!(EdDsaPublicKey::from_key_blob(&public_blob(&fields)).is_none());
        assert!(EdDsaPublicKey::from_xml(&public_xml(&fields)).is_none());

        let mut fields = private.serial_fields();
        fields[3] = three_n;
        let refs: Vec<&BigUint> = fields.iter().collect();
        assert!(EdDsaPrivateKey::from_key_blob(&encode_biguints(&refs)).is_none());
    }

    /// A signature whose `R` is shifted by a point `T` of order 8 fails the
    /// uncofactored equation: `S·G` and `e·A` lie in the subgroup of order
    /// `n`, so `R + T` cannot equal `S·G − e·A`. The same signature with the
    /// honest `R` verifies, so the equation alone rejects the small-order
    /// component without an `[n]R` check.
    #[test]
    fn verify_rejects_a_nonce_point_with_a_small_order_component() {
        let curve = ed25519();
        let t = (0u64..64)
            .filter_map(|y| curve.decode_point(&BigUint::from_u64(y).to_le_bytes_padded(32)))
            .map(|point| curve.scalar_mul(&point, &curve.n))
            .find(|t| !curve.mul_by_pow2(t, 2).is_neutral())
            .expect("some [n]P has order 8");
        assert!(curve.mul_by_pow2(&t, 3).is_neutral());

        let (public, private) = EdDsa::generate(curve.clone(), &mut rng());
        let sig = private
            .sign_message::<Sha512, _>(b"small order", &mut rng())
            .expect("sign");
        assert!(public.verify_message::<Sha512>(b"small order", &sig));
        let shifted = EdDsaSignature {
            r_point: curve.add(&sig.r_point, &t),
            s: sig.s.clone(),
        };
        assert!(curve.is_canonical_point(&shifted.r_point));
        assert!(!curve.is_in_prime_subgroup(&shifted.r_point));
        assert!(!public.verify_message::<Sha512>(b"small order", &shifted));
    }

    /// The neutral element is not a nonce point, whether flagged or spelled
    /// as `(0, 1)`: the blob decoder refuses both spellings.
    #[test]
    fn signature_binary_rejects_a_neutral_r() {
        let curve = ed25519();
        let blob = encode_biguints(&[&BigUint::zero(), &BigUint::one(), &BigUint::one()]);
        assert!(EdDsaSignature::from_key_blob(&blob, &curve).is_none());
    }

    #[test]
    fn private_key_equality_compares_scalars() {
        let curve = ed25519();
        let key = |d: &BigUint| {
            EdDsa::from_secret_scalar(curve.clone(), d)
                .expect("scalar in range")
                .1
        };
        let seven = BigUint::from_u64(7);
        let top = curve.n.sub(&BigUint::one());
        assert!(key(&seven) == key(&seven));
        assert!(key(&seven) != key(&BigUint::from_u64(8)));
        // Scalars whose minimal encodings differ in length still compare by value.
        assert!(key(&seven) != key(&top));
        assert!(key(&top) == key(&top));
    }
}
