#!/usr/bin/env python3
"""Generate Apple go-fast speedup radar chart SVG."""

from __future__ import annotations

import math
from pathlib import Path


OUTPUT = Path(__file__).with_name("apple-go-fast-radar.svg")

FAST_COLOR = "#0f766e"
BG_COLOR = "#fbf8f1"
GRID_COLOR = "#c9c2b7"
AXIS_COLOR = "#a79d90"
TEXT_COLOR = "#342f29"
SUBTEXT_COLOR = "#6b6257"

WIDTH = 560
HEIGHT = 590
CX = 280.0
CY = 245.0
RADIUS = 180.0
MIN_VALUE = 1.0
MAX_VALUE = 32.0

LABELS = [
    "AES-128",
    "AES-256",
    "SHA-256",
    "GHASH",
    "ChaCha20",
    "SHAKE",
]

SPEEDUPS = [19.50, 22.81, 6.63, 12.75, 1.53, 1.07]
SCALE_LABELS = [1, 2, 4, 8, 16, 32]


def polar(radius: float, angle: float) -> tuple[float, float]:
    return (CX + radius * math.cos(angle), CY + radius * math.sin(angle))


def fmt_points(points: list[tuple[float, float]]) -> str:
    return " ".join(f"{x:.1f},{y:.1f}" for x, y in points)


def value_radius(value: float) -> float:
    clamped = min(max(value, MIN_VALUE), MAX_VALUE)
    span = math.log2(MAX_VALUE / MIN_VALUE)
    return RADIUS * math.log2(clamped / MIN_VALUE) / span


def label_anchor(x: float) -> str:
    if x < CX - 20:
        return "end"
    if x > CX + 20:
        return "start"
    return "middle"


def label_y(base_y: float) -> float:
    if base_y < CY - RADIUS + 30:
        return base_y
    if base_y > CY + RADIUS - 30:
        return base_y + 12
    return base_y + 4


def generate_svg() -> str:
    n = len(LABELS)
    angles = [(-math.pi / 2) + (2 * math.pi * i / n) for i in range(n)]

    rings = []
    for ring in range(1, len(SCALE_LABELS) + 1):
        r = RADIUS * ring / len(SCALE_LABELS)
        rings.append(fmt_points([polar(r, a) for a in angles]))

    axes = [polar(RADIUS, a) for a in angles]
    speedup_poly = fmt_points([polar(value_radius(v), a) for v, a in zip(SPEEDUPS, angles)])

    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 {WIDTH} {HEIGHT}" role="img" aria-labelledby="title desc">',
        "  <!-- Generated by assets/generate_apple_go_fast_radar.py -->",
        '  <title id="title">Apple go-fast speedups over baseline/reference</title>',
        '  <desc id="desc">Log-scaled radar chart showing speedup multipliers for Apple-Silicon alternative kernels relative to baseline/reference implementations.</desc>',
        "  <style>",
        f"    .bg {{ fill: {BG_COLOR}; }}",
        f"    .grid {{ fill: none; stroke: {GRID_COLOR}; stroke-width: 1; }}",
        f"    .axis {{ stroke: {AXIS_COLOR}; stroke-width: 1; }}",
        f'    .label {{ fill: {TEXT_COLOR}; font: 12px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}',
        f'    .small {{ fill: {SUBTEXT_COLOR}; font: 11px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}',
        f"    .speedup-fill {{ fill: {FAST_COLOR}; fill-opacity: 0.24; stroke: {FAST_COLOR}; stroke-width: 2; }}",
        "  </style>",
        "",
        f'  <rect class="bg" x="0" y="0" width="{WIDTH}" height="{HEIGHT}" rx="16" />',
        "",
    ]

    for ring in rings:
        lines.append(f'  <polygon class="grid" points="{ring}" />')

    lines.append("")

    for x, y in axes:
        lines.append(f'  <line class="axis" x1="{CX:.0f}" y1="{CY:.0f}" x2="{x:.1f}" y2="{y:.1f}" />')

    lines.extend(
        [
            "",
            f'  <polygon class="speedup-fill" points="{speedup_poly}" />',
            "",
        ]
    )

    for i, label in enumerate(SCALE_LABELS, start=1):
        y = CY - (RADIUS * i / len(SCALE_LABELS))
        lines.append(f'  <text class="small" x="316" y="{y + 1:.0f}">{label}x</text>')

    lines.append("")

    for label, angle in zip(LABELS, angles):
        x, y = polar(RADIUS + 24, angle)
        anchor = label_anchor(x)
        y = label_y(y)
        lines.append(f'  <text class="label" x="{x:.1f}" y="{y:.1f}" text-anchor="{anchor}">{label}</text>')

    lines.extend(
        [
            "",
            '  <text class="label" x="20" y="538">Apple-Silicon Go-Fast Speedup (log scale)</text>',
            '  <text class="small" x="20" y="556">Speedup over baseline/reference; GHASH uses Ct software reference</text>',
            '  <rect x="372" y="539" width="14" height="14" fill="#0f766e" rx="2" />',
            '  <text class="small" x="392" y="550">Go-fast / baseline</text>',
            "</svg>",
        ]
    )

    return "\n".join(lines) + "\n"


def main() -> None:
    OUTPUT.write_text(generate_svg(), encoding="utf-8")


if __name__ == "__main__":
    main()
