#!/usr/bin/env python3
"""Generate a symmetric M1-vs-Xeon throughput radar chart SVG."""

from __future__ import annotations

import math
from pathlib import Path


OUTPUT = Path(__file__).with_name("symmetric-platform-radar.svg")

M1_COLOR = "#0f766e"
XEON_COLOR = "#1d4ed8"
BG_COLOR = "#fbf8f1"
GRID_COLOR = "#c9c2b7"
AXIS_COLOR = "#a79d90"
TEXT_COLOR = "#342f29"
SUBTEXT_COLOR = "#6b6257"

WIDTH = 620
HEIGHT = 620
CX = 310.0
CY = 250.0
RADIUS = 185.0
MIN_VALUE = 2.0
MAX_VALUE = 1024.0

LABELS = [
    "AES-128",
    "Camellia-128",
    "CAST-128",
    "DES",
    "PRESENT-80",
    "Magma",
    "Grasshopper",
    "SM4",
    "SEED",
    "Twofish-256",
    "SNOW 3G",
    "ZUC-128",
    "ChaCha20",
]

M1_VALUES = [356.9, 97.56, 158.3, 57.0, 8.49, 36.97, 21.19, 149.7, 47.63, 10.91, 336.7, 361.7, 533.0]
XEON_VALUES = [184.2, 89.81, 112.5, 56.74, 2.422, 39.47, 9.946, 118.7, 46.67, 20.42, 245.3, 222.0, 306.4]
SCALE_LABELS = [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]


def polar(radius: float, angle: float) -> tuple[float, float]:
    return (CX + radius * math.cos(angle), CY + radius * math.sin(angle))


def fmt_points(points: list[tuple[float, float]]) -> str:
    return " ".join(f"{x:.1f},{y:.1f}" for x, y in points)


def value_radius(value: float) -> float:
    clamped = min(max(value, MIN_VALUE), MAX_VALUE)
    span = math.log2(MAX_VALUE / MIN_VALUE)
    return RADIUS * math.log2(clamped / MIN_VALUE) / span


def label_anchor(x: float) -> str:
    if x < CX - 20:
        return "end"
    if x > CX + 20:
        return "start"
    return "middle"


def label_y(base_y: float) -> float:
    if base_y < CY - RADIUS + 30:
        return base_y
    if base_y > CY + RADIUS - 30:
        return base_y + 12
    return base_y + 4


def generate_svg() -> str:
    n = len(LABELS)
    angles = [(-math.pi / 2) + (2 * math.pi * i / n) for i in range(n)]

    rings = []
    for ring in range(1, len(SCALE_LABELS) + 1):
        r = RADIUS * ring / len(SCALE_LABELS)
        rings.append(fmt_points([polar(r, a) for a in angles]))

    axes = [polar(RADIUS, a) for a in angles]
    m1_poly = fmt_points([polar(value_radius(v), a) for v, a in zip(M1_VALUES, angles)])
    xeon_poly = fmt_points([polar(value_radius(v), a) for v, a in zip(XEON_VALUES, angles)])

    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 {WIDTH} {HEIGHT}" role="img" aria-labelledby="title desc">',
        "  <!-- Generated by assets/generate_symmetric_platform_radar.py -->",
        '  <title id="title">Symmetric throughput: M1 Max vs Xeon 6740E</title>',
        '  <desc id="desc">Log-scaled radar chart comparing representative fast-path symmetric throughput for Apple M1 Max and Intel Xeon 6740E.</desc>',
        "  <style>",
        f"    .bg {{ fill: {BG_COLOR}; }}",
        f"    .grid {{ fill: none; stroke: {GRID_COLOR}; stroke-width: 1; }}",
        f"    .axis {{ stroke: {AXIS_COLOR}; stroke-width: 1; }}",
        f'    .label {{ fill: {TEXT_COLOR}; font: 12px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}',
        f'    .small {{ fill: {SUBTEXT_COLOR}; font: 11px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}',
        f"    .m1-fill {{ fill: {M1_COLOR}; fill-opacity: 0.18; stroke: {M1_COLOR}; stroke-width: 2; }}",
        f"    .xeon-fill {{ fill: {XEON_COLOR}; fill-opacity: 0.18; stroke: {XEON_COLOR}; stroke-width: 2; }}",
        "  </style>",
        "",
        f'  <rect class="bg" x="0" y="0" width="{WIDTH}" height="{HEIGHT}" rx="16" />',
        "",
    ]

    for ring in rings:
        lines.append(f'  <polygon class="grid" points="{ring}" />')
    lines.append("")
    for x, y in axes:
        lines.append(f'  <line class="axis" x1="{CX:.0f}" y1="{CY:.0f}" x2="{x:.1f}" y2="{y:.1f}" />')

    lines.extend(
        [
            "",
            f'  <polygon class="m1-fill" points="{m1_poly}" />',
            f'  <polygon class="xeon-fill" points="{xeon_poly}" />',
            "",
        ]
    )

    for i, label in enumerate(SCALE_LABELS, start=1):
        y = CY - (RADIUS * i / len(SCALE_LABELS))
        lines.append(f'  <text class="small" x="350" y="{y + 1:.0f}">{label}</text>')

    lines.append("")
    for label, angle in zip(LABELS, angles):
        x, y = polar(RADIUS + 24, angle)
        lines.append(f'  <text class="label" x="{x:.1f}" y="{label_y(y):.1f}" text-anchor="{label_anchor(x)}">{label}</text>')

    lines.extend(
        [
            "",
            '  <text class="label" x="20" y="560">Symmetric Throughput Comparison (fast path, log scale)</text>',
            '  <text class="small" x="20" y="578">M1 Max (wigner.local) vs Xeon 6740E (ssh.soe.ucsc.edu), MiB/s</text>',
            '  <rect x="404" y="548" width="14" height="14" fill="#0f766e" rx="2" />',
            '  <text class="small" x="424" y="559">M1 Max</text>',
            '  <rect x="404" y="570" width="14" height="14" fill="#1d4ed8" rx="2" />',
            '  <text class="small" x="424" y="581">Xeon 6740E</text>',
            "</svg>",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    OUTPUT.write_text(generate_svg(), encoding="utf-8")


if __name__ == "__main__":
    main()
