#!/usr/bin/env python3
"""Generate x86 go-fast throughput radar chart SVG."""

from __future__ import annotations

import math
from pathlib import Path

from radar_label_layout import default_offset_y, spread_label_positions


OUTPUT = Path(__file__).with_name("x86-go-fast-radar.svg")

FAST_COLOR = "#0f766e"
BASE_COLOR = "#b45309"
BG_COLOR = "#fbf8f1"
GRID_COLOR = "#c9c2b7"
AXIS_COLOR = "#a79d90"
TEXT_COLOR = "#342f29"
SUBTEXT_COLOR = "#6b6257"

WIDTH = 620
HEIGHT = 650
CX = 310.0
CY = 250.0
RADIUS = 180.0

DATA = [
    ("AES-128", "MiB/s", 2557.36, 248.95),
    ("AES-256", "MiB/s", 2043.97, 185.42),
    ("GHASH", "Mops/s", 42.39, 2.54),
]

RING_LABELS = [20, 40, 60, 80, 100]


def polar(radius: float, angle: float) -> tuple[float, float]:
    return (CX + radius * math.cos(angle), CY + radius * math.sin(angle))


def fmt_points(points: list[tuple[float, float]]) -> str:
    return " ".join(f"{x:.1f},{y:.1f}" for x, y in points)


def normalized_radius(value: float, axis_max: float) -> float:
    if axis_max <= 0:
        return 0.0
    return RADIUS * (value / axis_max)


def label_anchor(x: float) -> str:
    if x < CX - 20:
        return "end"
    if x > CX + 20:
        return "start"
    return "middle"


def fmt_value(value: float) -> str:
    if value >= 1000:
        return f"{value:,.0f}"
    if value >= 100:
        return f"{value:.1f}"
    return f"{value:.2f}"


def generate_svg() -> str:
    labels = [entry[0] for entry in DATA]
    n = len(labels)
    angles = [(-math.pi / 2) + (2 * math.pi * i / n) for i in range(n)]
    axis_maxima = [max(entry[2], entry[3]) for entry in DATA]

    rings = []
    for ring in range(1, len(RING_LABELS) + 1):
        r = RADIUS * ring / len(RING_LABELS)
        rings.append(fmt_points([polar(r, a) for a in angles]))

    axes = [polar(RADIUS, a) for a in angles]
    fast_poly = fmt_points(
        [
            polar(normalized_radius(entry[2], axis_max), angle)
            for entry, axis_max, angle in zip(DATA, axis_maxima, angles)
        ]
    )
    base_poly = fmt_points(
        [
            polar(normalized_radius(entry[3], axis_max), angle)
            for entry, axis_max, angle in zip(DATA, axis_maxima, angles)
        ]
    )

    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 {WIDTH} {HEIGHT}" role="img" aria-labelledby="title desc">',
        "  <!-- Generated by assets/generate_x86_go_fast_radar.py -->",
        '  <title id="title">x86 go-fast throughput curves: go-fast vs baseline/reference</title>',
        '  <desc id="desc">Radar chart with two curves (go-fast and baseline/reference). Each axis is normalized independently so both throughput values can be shown despite unit differences.</desc>',
        "  <style>",
        f"    .bg {{ fill: {BG_COLOR}; }}",
        f"    .grid {{ fill: none; stroke: {GRID_COLOR}; stroke-width: 1; }}",
        f"    .axis {{ stroke: {AXIS_COLOR}; stroke-width: 1; }}",
        f'    .label {{ fill: {TEXT_COLOR}; font: 12px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}',
        f'    .small {{ fill: {SUBTEXT_COLOR}; font: 11px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}',
        f"    .base-fill {{ fill: {BASE_COLOR}; fill-opacity: 0.16; stroke: {BASE_COLOR}; stroke-width: 2; }}",
        f"    .fast-fill {{ fill: {FAST_COLOR}; fill-opacity: 0.24; stroke: {FAST_COLOR}; stroke-width: 2; }}",
        "  </style>",
        "",
        f'  <rect class="bg" x="0" y="0" width="{WIDTH}" height="{HEIGHT}" rx="16" />',
        "",
    ]

    for ring in rings:
        lines.append(f'  <polygon class="grid" points="{ring}" />')

    lines.append("")

    for x, y in axes:
        lines.append(f'  <line class="axis" x1="{CX:.0f}" y1="{CY:.0f}" x2="{x:.1f}" y2="{y:.1f}" />')

    lines.extend(
        [
            "",
            f'  <polygon class="base-fill" points="{base_poly}" />',
            f'  <polygon class="fast-fill" points="{fast_poly}" />',
            "",
        ]
    )

    for i, label in enumerate(RING_LABELS, start=1):
        y = CY - (RADIUS * i / len(RING_LABELS))
        lines.append(f'  <text class="small" x="347" y="{y + 1:.0f}">{label}%</text>')

    lines.append("")

    label_entries: list[dict[str, float | str]] = []
    for (label, unit, fast, base), angle in zip(DATA, angles):
        x, y = polar(RADIUS + 24, angle)
        label_entries.append(
            {
                "label": label,
                "detail": f"{fmt_value(fast)} / {fmt_value(base)} {unit}",
                "x": x,
                "y": default_offset_y(y, CY, RADIUS),
                "anchor": label_anchor(x),
            }
        )

    spread_label_positions(
        label_entries,
        min_gap=30.0,
        min_y=CY - RADIUS - 18.0,
        max_y=CY + RADIUS + 24.0,
    )

    for entry in label_entries:
        x = float(entry["x"])
        y = float(entry["y"])
        anchor = str(entry["anchor"])
        lines.append(f'  <text class="label" x="{x:.1f}" y="{y:.1f}" text-anchor="{anchor}">{entry["label"]}</text>')
        lines.append(f'  <text class="small" x="{x:.1f}" y="{y + 14:.1f}" text-anchor="{anchor}">{entry["detail"]}</text>')

    lines.extend(
        [
            "",
            '  <text class="label" x="20" y="566">x86 Go-Fast Throughput Curves (per-axis normalized)</text>',
            '  <text class="small" x="20" y="584">Published set uses a ≥5× promotion gate; GHASH baseline is Ct software reference</text>',
            '  <rect x="20" y="606" width="14" height="14" fill="#0f766e" rx="2" />',
            '  <text class="small" x="40" y="617">Go-fast throughput</text>',
            '  <rect x="184" y="606" width="14" height="14" fill="#b45309" rx="2" />',
            '  <text class="small" x="204" y="617">Baseline/reference throughput</text>',
            "</svg>",
        ]
    )

    return "\n".join(lines) + "\n"


def main() -> None:
    OUTPUT.write_text(generate_svg(), encoding="utf-8")


if __name__ == "__main__":
    main()
