#!/usr/bin/env python3
"""Generate a public-key M1-vs-Xeon throughput radar chart SVG."""

from __future__ import annotations

import math
from pathlib import Path


OUTPUT = Path(__file__).with_name("public-key-platform-radar.svg")

M1_COLOR = "#0f766e"
XEON_COLOR = "#1d4ed8"
BG_COLOR = "#fbf8f1"
GRID_COLOR = "#c9c2b7"
AXIS_COLOR = "#a79d90"
TEXT_COLOR = "#342f29"
SUBTEXT_COLOR = "#6b6257"

WIDTH = 640
HEIGHT = 640
CX = 320.0
CY = 255.0
RADIUS = 190.0
MIN_VALUE = 64.0
MAX_VALUE = 32_768.0

LABELS = [
    "RSA-1024 Encrypt",
    "RSA-1024 Decrypt",
    "RSA-2048 Sign",
    "ECDSA Sign",
    "ECDSA Verify",
    "ECDH Agree",
    "ECIES Encrypt",
    "ECIES Decrypt",
    "Ed25519 Sign",
    "Ed25519 Verify",
    "Edwards DH Agree",
    "Edwards ElGamal Dec",
]

# values are ops/sec (1000 / ms-op)
M1_VALUES = [
    22_686.0,
    2_946.4,
    543.8,
    456.0,
    241.4,
    480.8,
    249.8,
    503.8,
    900.9,
    298.7,
    993.0,
    620.7,
]
XEON_VALUES = [
    16_139.4,
    639.0,
    86.9,
    315.4,
    165.8,
    318.0,
    173.3,
    352.7,
    637.8,
    186.3,
    624.6,
    406.2,
]
SCALE_LABELS = [64, 128, 256, 512, 1_024, 2_048, 4_096, 8_192, 16_384, 32_768]


def polar(radius: float, angle: float) -> tuple[float, float]:
    return (CX + radius * math.cos(angle), CY + radius * math.sin(angle))


def fmt_points(points: list[tuple[float, float]]) -> str:
    return " ".join(f"{x:.1f},{y:.1f}" for x, y in points)


def value_radius(value: float) -> float:
    clamped = min(max(value, MIN_VALUE), MAX_VALUE)
    span = math.log2(MAX_VALUE / MIN_VALUE)
    return RADIUS * math.log2(clamped / MIN_VALUE) / span


def label_anchor(x: float) -> str:
    if x < CX - 20:
        return "end"
    if x > CX + 20:
        return "start"
    return "middle"


def label_y(base_y: float) -> float:
    if base_y < CY - RADIUS + 30:
        return base_y
    if base_y > CY + RADIUS - 30:
        return base_y + 12
    return base_y + 4


def generate_svg() -> str:
    n = len(LABELS)
    angles = [(-math.pi / 2) + (2 * math.pi * i / n) for i in range(n)]

    rings = []
    for ring in range(1, len(SCALE_LABELS) + 1):
        r = RADIUS * ring / len(SCALE_LABELS)
        rings.append(fmt_points([polar(r, a) for a in angles]))

    axes = [polar(RADIUS, a) for a in angles]
    m1_poly = fmt_points([polar(value_radius(v), a) for v, a in zip(M1_VALUES, angles)])
    xeon_poly = fmt_points([polar(value_radius(v), a) for v, a in zip(XEON_VALUES, angles)])

    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 {WIDTH} {HEIGHT}" role="img" aria-labelledby="title desc">',
        "  <!-- Generated by assets/generate_pk_platform_radar.py -->",
        '  <title id="title">Public-key throughput: M1 Max vs Xeon 6740E</title>',
        '  <desc id="desc">Log-scaled radar chart comparing representative public-key throughput (ops/sec) for Apple M1 Max and Intel Xeon 6740E.</desc>',
        "  <style>",
        f"    .bg {{ fill: {BG_COLOR}; }}",
        f"    .grid {{ fill: none; stroke: {GRID_COLOR}; stroke-width: 1; }}",
        f"    .axis {{ stroke: {AXIS_COLOR}; stroke-width: 1; }}",
        f'    .label {{ fill: {TEXT_COLOR}; font: 12px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}',
        f'    .small {{ fill: {SUBTEXT_COLOR}; font: 11px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}',
        f"    .m1-fill {{ fill: {M1_COLOR}; fill-opacity: 0.18; stroke: {M1_COLOR}; stroke-width: 2; }}",
        f"    .xeon-fill {{ fill: {XEON_COLOR}; fill-opacity: 0.18; stroke: {XEON_COLOR}; stroke-width: 2; }}",
        "  </style>",
        "",
        f'  <rect class="bg" x="0" y="0" width="{WIDTH}" height="{HEIGHT}" rx="16" />',
        "",
    ]

    for ring in rings:
        lines.append(f'  <polygon class="grid" points="{ring}" />')
    lines.append("")
    for x, y in axes:
        lines.append(f'  <line class="axis" x1="{CX:.0f}" y1="{CY:.0f}" x2="{x:.1f}" y2="{y:.1f}" />')

    lines.extend(
        [
            "",
            f'  <polygon class="m1-fill" points="{m1_poly}" />',
            f'  <polygon class="xeon-fill" points="{xeon_poly}" />',
            "",
        ]
    )

    for i, label in enumerate(SCALE_LABELS, start=1):
        y = CY - (RADIUS * i / len(SCALE_LABELS))
        lines.append(f'  <text class="small" x="366" y="{y + 1:.0f}">{label}</text>')

    lines.append("")
    for label, angle in zip(LABELS, angles):
        x, y = polar(RADIUS + 26, angle)
        lines.append(f'  <text class="label" x="{x:.1f}" y="{label_y(y):.1f}" text-anchor="{label_anchor(x)}">{label}</text>')

    lines.extend(
        [
            "",
            '  <text class="label" x="20" y="578">Public-key Throughput Comparison (ops/sec, log scale)</text>',
            '  <text class="small" x="20" y="596">M1 Max (wigner.local) vs Xeon 6740E (ssh.soe.ucsc.edu)</text>',
            '  <rect x="424" y="566" width="14" height="14" fill="#0f766e" rx="2" />',
            '  <text class="small" x="444" y="577">M1 Max</text>',
            '  <rect x="424" y="588" width="14" height="14" fill="#1d4ed8" rx="2" />',
            '  <text class="small" x="444" y="599">Xeon 6740E</text>',
            "</svg>",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    OUTPUT.write_text(generate_svg(), encoding="utf-8")


if __name__ == "__main__":
    main()
