#!/usr/bin/env python3
"""Generate a symmetric M4-vs-EPYC throughput radar chart SVG."""

from __future__ import annotations

import math
from pathlib import Path

from radar_label_layout import default_offset_y, spread_label_positions


OUTPUT = Path(__file__).with_name("symmetric-platform-radar.svg")

APPLE_COLOR = "#0f766e"
XEON_COLOR = "#1d4ed8"
BG_COLOR = "#fbf8f1"
GRID_COLOR = "#c9c2b7"
AXIS_COLOR = "#a79d90"
TEXT_COLOR = "#342f29"
SUBTEXT_COLOR = "#6b6257"

WIDTH = 620
HEIGHT = 650
CX = 310.0
CY = 250.0
RADIUS = 185.0
MIN_VALUE = 2.0
MAX_VALUE = 1024.0

LABELS = [
    "AES-128",
    "Camellia-128",
    "CAST-128",
    "DES",
    "PRESENT-80",
    "Magma",
    "Grasshopper",
    "SM4",
    "SEED",
    "Twofish-256",
    "SNOW 3G",
    "ZUC-128",
    "ChaCha20",
]

APPLE_VALUES = [480.2, 140.1, 310.1, 78.2, 12.37, 60.38, 25.62, 184.0, 73.57, 13.97, 480.1, 520.7, 775.9]
XEON_VALUES = [230.6, 85.6, 103.7, 54.64, 2.735, 41.29, 12.74, 128.2, 46.13, 7.167, 272.7, 266.0, 414.6]
SCALE_LABELS = [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]


def polar(radius: float, angle: float) -> tuple[float, float]:
    return (CX + radius * math.cos(angle), CY + radius * math.sin(angle))


def fmt_points(points: list[tuple[float, float]]) -> str:
    return " ".join(f"{x:.1f},{y:.1f}" for x, y in points)


def value_radius(value: float) -> float:
    clamped = min(max(value, MIN_VALUE), MAX_VALUE)
    span = math.log2(MAX_VALUE / MIN_VALUE)
    return RADIUS * math.log2(clamped / MIN_VALUE) / span


def label_anchor(x: float) -> str:
    if x < CX - 20:
        return "end"
    if x > CX + 20:
        return "start"
    return "middle"


def generate_svg() -> str:
    n = len(LABELS)
    angles = [(-math.pi / 2) + (2 * math.pi * i / n) for i in range(n)]

    rings = []
    for ring in range(1, len(SCALE_LABELS) + 1):
        r = RADIUS * ring / len(SCALE_LABELS)
        rings.append(fmt_points([polar(r, a) for a in angles]))

    axes = [polar(RADIUS, a) for a in angles]
    apple_poly = fmt_points([polar(value_radius(v), a) for v, a in zip(APPLE_VALUES, angles)])
    xeon_poly = fmt_points([polar(value_radius(v), a) for v, a in zip(XEON_VALUES, angles)])

    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 {WIDTH} {HEIGHT}" role="img" aria-labelledby="title desc">',
        "  <!-- Generated by assets/generate_symmetric_platform_radar.py -->",
        '  <title id="title">Symmetric throughput: M4 Pro vs AMD EPYC 7452</title>',
        '  <desc id="desc">Log-scaled radar chart comparing representative fast-path symmetric throughput for Apple M4 Pro and AMD EPYC 7452.</desc>',
        "  <style>",
        f"    .bg {{ fill: {BG_COLOR}; }}",
        f"    .grid {{ fill: none; stroke: {GRID_COLOR}; stroke-width: 1; }}",
        f"    .axis {{ stroke: {AXIS_COLOR}; stroke-width: 1; }}",
        f'    .label {{ fill: {TEXT_COLOR}; font: 12px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}',
        f'    .small {{ fill: {SUBTEXT_COLOR}; font: 11px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}',
        f"    .apple-fill {{ fill: {APPLE_COLOR}; fill-opacity: 0.18; stroke: {APPLE_COLOR}; stroke-width: 2; }}",
        f"    .xeon-fill {{ fill: {XEON_COLOR}; fill-opacity: 0.18; stroke: {XEON_COLOR}; stroke-width: 2; }}",
        "  </style>",
        "",
        f'  <rect class="bg" x="0" y="0" width="{WIDTH}" height="{HEIGHT}" rx="16" />',
        "",
    ]

    for ring in rings:
        lines.append(f'  <polygon class="grid" points="{ring}" />')
    lines.append("")
    for x, y in axes:
        lines.append(f'  <line class="axis" x1="{CX:.0f}" y1="{CY:.0f}" x2="{x:.1f}" y2="{y:.1f}" />')

    lines.extend(
        [
            "",
            f'  <polygon class="apple-fill" points="{apple_poly}" />',
            f'  <polygon class="xeon-fill" points="{xeon_poly}" />',
            "",
        ]
    )

    for i, label in enumerate(SCALE_LABELS, start=1):
        y = CY - (RADIUS * i / len(SCALE_LABELS))
        lines.append(f'  <text class="small" x="350" y="{y + 1:.0f}">{label}</text>')

    lines.append("")
    label_entries: list[dict[str, float | str]] = []
    for label, angle in zip(LABELS, angles):
        x, y = polar(RADIUS + 24, angle)
        label_entries.append(
            {
                "label": label,
                "x": x,
                "y": default_offset_y(y, CY, RADIUS),
                "anchor": label_anchor(x),
            }
        )

    spread_label_positions(
        label_entries,
        min_gap=14.0,
        min_y=CY - RADIUS - 16.0,
        max_y=CY + RADIUS + 30.0,
    )

    for entry in label_entries:
        lines.append(
            f'  <text class="label" x="{float(entry["x"]):.1f}" y="{float(entry["y"]):.1f}" '
            f'text-anchor="{entry["anchor"]}">{entry["label"]}</text>'
        )

    lines.extend(
        [
            "",
            '  <text class="label" x="20" y="560">Symmetric Throughput Comparison (fast path, log scale)</text>',
            '  <text class="small" x="20" y="578">M4 Pro (Dyson.local) vs AMD EPYC 7452 (moore.soe.ucsc.edu), MiB/s</text>',
            '  <rect x="20" y="600" width="14" height="14" fill="#0f766e" rx="2" />',
            '  <text class="small" x="40" y="611">M4 Pro</text>',
            '  <rect x="132" y="600" width="14" height="14" fill="#1d4ed8" rx="2" />',
            '  <text class="small" x="152" y="611">AMD EPYC 7452</text>',
            "</svg>",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    OUTPUT.write_text(generate_svg(), encoding="utf-8")


if __name__ == "__main__":
    main()
