#!/usr/bin/env python3
"""Generate the fast-vs-ct radar chart SVG used in ANALYSIS.md.

The SVG is committed so GitHub renders it reliably. This script keeps the chart
layout reproducible and avoids hand-editing point lists whenever benchmark
values or representative labels change.
"""

from __future__ import annotations

import math
from pathlib import Path


OUTPUT = Path(__file__).with_name("fast-vs-ct-radar.svg")

FAST_COLOR = "#0f766e"
CT_COLOR = "#b45309"
BG_COLOR = "#fbf8f1"
GRID_COLOR = "#c9c2b7"
AXIS_COLOR = "#a79d90"
TEXT_COLOR = "#342f29"
SUBTEXT_COLOR = "#6b6257"

WIDTH = 560
HEIGHT = 590
CX = 280.0
CY = 245.0
RADIUS = 180.0
MIN_VALUE = 4.0
MAX_VALUE = 1024.0

LABELS = [
    "AES-128",
    "AES-192",
    "AES-256",
    "CAST-128",
    "DES",
    "PRESENT-80",
    "Camellia-128",
    "Magma",
    "Grasshopper",
    "SM4",
    "SEED-128",
    "Twofish-256",
    "SNOW-3G",
    "ZUC-128",
]

FAST_VALUES = [492.1, 415.5, 342.5, 311.3, 75.26, 12.37, 147.7, 60.13, 25.05, 183.8, 70.68, 13.02, 492.8, 520.2]
CT_VALUES = [65.79, 53.14, 45.44, 3.99, 7.912, 3.943, 6.356, 13.85, 4.061, 6.674, 4.534, 2.206, 21.05, 27.05]
SCALE_LABELS = [8, 16, 32, 64, 128, 256, 512, 1024]


def polar(radius: float, angle: float) -> tuple[float, float]:
    return (CX + radius * math.cos(angle), CY + radius * math.sin(angle))


def fmt_points(points: list[tuple[float, float]]) -> str:
    return " ".join(f"{x:.1f},{y:.1f}" for x, y in points)


def value_radius(value: float) -> float:
    clamped = min(max(value, MIN_VALUE), MAX_VALUE)
    span = math.log2(MAX_VALUE / MIN_VALUE)
    return RADIUS * math.log2(clamped / MIN_VALUE) / span


def label_anchor(x: float) -> str:
    if x < CX - 20:
        return "end"
    if x > CX + 20:
        return "start"
    return "middle"


def label_y(base_y: float) -> float:
    if base_y < CY - RADIUS + 30:
        return base_y
    if base_y > CY + RADIUS - 30:
        return base_y + 12
    return base_y + 4


def generate_svg() -> str:
    n = len(LABELS)
    angles = [(-math.pi / 2) + (2 * math.pi * i / n) for i in range(n)]

    rings = []
    for ring in range(1, 9):
        r = RADIUS * ring / 8
        rings.append(fmt_points([polar(r, a) for a in angles]))

    axes = [polar(RADIUS, a) for a in angles]
    fast_poly = fmt_points([polar(value_radius(v), a) for v, a in zip(FAST_VALUES, angles)])
    ct_poly = fmt_points([polar(value_radius(v), a) for v, a in zip(CT_VALUES, angles)])

    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {HEIGHT}" role="img" aria-labelledby="title desc">',
        "  <!-- Generated by assets/generate_fast_vs_ct_radar.py -->",
        '  <title id="title">Fast vs Ct throughput radar chart (log scale, representative variants)</title>',
        '  <desc id="desc">Log-scaled radar chart comparing representative fast and constant-time throughput for AES, CAST-128, DES, PRESENT, Camellia, Magma, Grasshopper, SM4, SEED, Twofish, SNOW 3G, and ZUC families.</desc>',
        "  <style>",
        f"    .bg {{ fill: {BG_COLOR}; }}",
        f"    .grid {{ fill: none; stroke: {GRID_COLOR}; stroke-width: 1; }}",
        f"    .axis {{ stroke: {AXIS_COLOR}; stroke-width: 1; }}",
        f'    .label {{ fill: {TEXT_COLOR}; font: 12px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}',
        f'    .small {{ fill: {SUBTEXT_COLOR}; font: 11px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}',
        f"    .fast-fill {{ fill: {FAST_COLOR}; fill-opacity: 0.20; stroke: {FAST_COLOR}; stroke-width: 2; }}",
        f"    .ct-fill {{ fill: {CT_COLOR}; fill-opacity: 0.24; stroke: {CT_COLOR}; stroke-width: 2; }}",
        f"    .legend-fast {{ fill: {FAST_COLOR}; }}",
        f"    .legend-ct {{ fill: {CT_COLOR}; }}",
        "  </style>",
        "",
        f'  <rect class="bg" x="0" y="0" width="{WIDTH}" height="{HEIGHT}" rx="16" />',
        "",
    ]

    for ring in rings:
        lines.append(f'  <polygon class="grid" points="{ring}" />')

    lines.append("")

    for x, y in axes:
        lines.append(f'  <line class="axis" x1="{CX:.0f}" y1="{CY:.0f}" x2="{x:.1f}" y2="{y:.1f}" />')

    lines.extend(
        [
            "",
            f'  <polygon class="fast-fill" points="{fast_poly}" />',
            f'  <polygon class="ct-fill" points="{ct_poly}" />',
            "",
        ]
    )

    for i, label in enumerate(SCALE_LABELS, start=1):
        y = CY - (RADIUS * i / 8)
        lines.append(f'  <text class="small" x="316" y="{y + 1:.0f}">{label}</text>')

    lines.append("")

    for label, angle in zip(LABELS, angles):
        x, y = polar(RADIUS + 24, angle)
        anchor = label_anchor(x)
        y = label_y(y)
        lines.append(f'  <text class="label" x="{x:.1f}" y="{y:.1f}" text-anchor="{anchor}">{label}</text>')

    lines.extend(
        [
            "",
            '  <text class="label" x="20" y="538">Fast vs Ct Throughput (log scale, representative variants)</text>',
            '  <text class="small" x="20" y="556">Radial scale is logarithmic, spanning 4 MiB/s to 1024 MiB/s</text>',
            "",
            '  <rect x="372" y="528" width="14" height="14" class="legend-fast" rx="2" />',
            '  <text class="small" x="392" y="539">Fast path</text>',
            '  <rect x="372" y="550" width="14" height="14" class="legend-ct" rx="2" />',
            '  <text class="small" x="392" y="561">Ct path</text>',
            "</svg>",
        ]
    )

    return "\n".join(lines) + "\n"


def main() -> None:
    OUTPUT.write_text(generate_svg(), encoding="utf-8")


if __name__ == "__main__":
    main()
