#!/usr/bin/env python3
"""Generate an ML-KEM throughput radar chart SVG (M1 Max vs Xeon 6740E)."""

from __future__ import annotations

import math
from pathlib import Path

from radar_label_layout import default_offset_y, spread_label_positions


OUTPUT = Path(__file__).with_name("mlkem-platform-radar.svg")

APPLE_COLOR = "#0f766e"
XEON_COLOR = "#1d4ed8"
BG_COLOR = "#fbf8f1"
GRID_COLOR = "#c9c2b7"
AXIS_COLOR = "#a79d90"
TEXT_COLOR = "#342f29"
SUBTEXT_COLOR = "#6b6257"

WIDTH = 640
HEIGHT = 640
CX = 320.0
CY = 255.0
RADIUS = 190.0
MIN_VALUE = 8_192.0
MAX_VALUE = 65_536.0

# Nine axes: keygen/encaps/decaps for each of 512, 768, 1024.
LABELS = [
    "512 Keygen",
    "512 Encaps",
    "512 Decaps",
    "768 Keygen",
    "768 Encaps",
    "768 Decaps",
    "1024 Keygen",
    "1024 Encaps",
    "1024 Decaps",
]

# ops/sec = 1000 / ms-op; source: POSTQUANTUM.md bench tables (M1 Max / Xeon 6740E).
APPLE_VALUES = [
    1_000 / 0.01947,   # 512 keygen
    1_000 / 0.01937,   # 512 encaps
    1_000 / 0.01935,   # 512 decaps
    1_000 / 0.03204,   # 768 keygen
    1_000 / 0.03123,   # 768 encaps
    1_000 / 0.03189,   # 768 decaps
    1_000 / 0.05098,   # 1024 keygen
    1_000 / 0.04864,   # 1024 encaps
    1_000 / 0.04946,   # 1024 decaps
]
XEON_VALUES = [
    1_000 / 0.02968,   # 512 keygen
    1_000 / 0.03102,   # 512 encaps
    1_000 / 0.03489,   # 512 decaps
    1_000 / 0.04913,   # 768 keygen
    1_000 / 0.05036,   # 768 encaps
    1_000 / 0.05708,   # 768 decaps
    1_000 / 0.07745,   # 1024 keygen
    1_000 / 0.07629,   # 1024 encaps
    1_000 / 0.08396,   # 1024 decaps
]
SCALE_LABELS = [8_192, 16_384, 32_768, 65_536]


def polar(radius: float, angle: float) -> tuple[float, float]:
    return (CX + radius * math.cos(angle), CY + radius * math.sin(angle))


def fmt_points(points: list[tuple[float, float]]) -> str:
    return " ".join(f"{x:.1f},{y:.1f}" for x, y in points)


def value_radius(value: float) -> float:
    clamped = min(max(value, MIN_VALUE), MAX_VALUE)
    span = math.log2(MAX_VALUE / MIN_VALUE)
    return RADIUS * math.log2(clamped / MIN_VALUE) / span


def label_anchor(x: float) -> str:
    if x < CX - 20:
        return "end"
    if x > CX + 20:
        return "start"
    return "middle"


def generate_svg() -> str:
    n = len(LABELS)
    angles = [(-math.pi / 2) + (2 * math.pi * i / n) for i in range(n)]

    rings = []
    for ring in range(1, len(SCALE_LABELS) + 1):
        r = RADIUS * ring / len(SCALE_LABELS)
        rings.append(fmt_points([polar(r, a) for a in angles]))

    axes = [polar(RADIUS, a) for a in angles]
    apple_poly = fmt_points([polar(value_radius(v), a) for v, a in zip(APPLE_VALUES, angles)])
    xeon_poly = fmt_points([polar(value_radius(v), a) for v, a in zip(XEON_VALUES, angles)])

    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 {WIDTH} {HEIGHT}" role="img" aria-labelledby="title desc">',
        "  <!-- Generated by assets/generate_mlkem_radar.py -->",
        '  <title id="title">ML-KEM throughput: M1 Max vs Xeon 6740E</title>',
        '  <desc id="desc">Log-scaled radar chart comparing ML-KEM throughput (ops/sec) for Apple M1 Max and Intel Xeon 6740E across all three parameter sets.</desc>',
        "  <style>",
        f"    .bg {{ fill: {BG_COLOR}; }}",
        f"    .grid {{ fill: none; stroke: {GRID_COLOR}; stroke-width: 1; }}",
        f"    .axis {{ stroke: {AXIS_COLOR}; stroke-width: 1; }}",
        f'    .label {{ fill: {TEXT_COLOR}; font: 12px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}',
        f'    .small {{ fill: {SUBTEXT_COLOR}; font: 11px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}',
        f"    .apple-fill {{ fill: {APPLE_COLOR}; fill-opacity: 0.18; stroke: {APPLE_COLOR}; stroke-width: 2; }}",
        f"    .xeon-fill {{ fill: {XEON_COLOR}; fill-opacity: 0.18; stroke: {XEON_COLOR}; stroke-width: 2; }}",
        "  </style>",
        "",
        f'  <rect class="bg" x="0" y="0" width="{WIDTH}" height="{HEIGHT}" rx="16" />',
        "",
    ]

    for ring in rings:
        lines.append(f'  <polygon class="grid" points="{ring}" />')
    lines.append("")
    for x, y in axes:
        lines.append(f'  <line class="axis" x1="{CX:.0f}" y1="{CY:.0f}" x2="{x:.1f}" y2="{y:.1f}" />')

    lines.extend(
        [
            "",
            f'  <polygon class="apple-fill" points="{apple_poly}" />',
            f'  <polygon class="xeon-fill" points="{xeon_poly}" />',
            "",
        ]
    )

    for i, label in enumerate(SCALE_LABELS, start=1):
        y = CY - (RADIUS * i / len(SCALE_LABELS))
        lines.append(f'  <text class="small" x="326" y="{y + 1:.0f}">{label:,}</text>')

    lines.append("")
    label_entries: list[dict[str, float | str]] = []
    for label, angle in zip(LABELS, angles):
        x, y = polar(RADIUS + 26, angle)
        label_entries.append(
            {
                "label": label,
                "x": x,
                "y": default_offset_y(y, CY, RADIUS),
                "anchor": label_anchor(x),
            }
        )

    spread_label_positions(
        label_entries,
        min_gap=14.0,
        min_y=CY - RADIUS - 16.0,
        max_y=CY + RADIUS + 30.0,
    )

    for entry in label_entries:
        lines.append(
            f'  <text class="label" x="{float(entry["x"]):.1f}" y="{float(entry["y"]):.1f}" '
            f'text-anchor="{entry["anchor"]}">{entry["label"]}</text>'
        )

    lines.extend(
        [
            "",
            '  <text class="label" x="20" y="578">ML-KEM Throughput Comparison (ops/sec, log scale)</text>',
            '  <text class="small" x="20" y="596">M1 Max (wigner.local) vs Intel Xeon 6740E (ssh.soe.ucsc.edu)</text>',
            f'  <rect x="424" y="566" width="14" height="14" fill="{APPLE_COLOR}" rx="2" />',
            '  <text class="small" x="444" y="577">M1 Max</text>',
            f'  <rect x="424" y="588" width="14" height="14" fill="{XEON_COLOR}" rx="2" />',
            '  <text class="small" x="444" y="599">Xeon 6740E</text>',
            "</svg>",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    OUTPUT.write_text(generate_svg(), encoding="utf-8")


if __name__ == "__main__":
    main()
