#!/usr/bin/env python3
"""Generate the public-key encrypt/decrypt radar chart SVG for ANALYSIS.md.

The chart is committed so GitHub renders it reliably. The radial scale uses
operations per second (derived from measured millisecond latencies), so farther
from the center means faster.
"""

from __future__ import annotations

import math
from pathlib import Path


OUTPUT = Path(__file__).with_name("public-key-encdec-radar.svg")

ENC_COLOR = "#0f766e"
DEC_COLOR = "#1d4ed8"
BG_COLOR = "#fbf8f1"
GRID_COLOR = "#c9c2b7"
AXIS_COLOR = "#a79d90"
TEXT_COLOR = "#342f29"
SUBTEXT_COLOR = "#6b6257"

WIDTH = 560
HEIGHT = 590
CX = 280.0
CY = 245.0
RADIUS = 180.0
MIN_VALUE = 100.0
MAX_VALUE = 30_000.0

LABELS = [
    "RSA",
    "ElGamal",
    "Paillier",
    "Cocks",
    "Rabin",
    "Schmidt-Samoa",
]

# Values are operations/second derived from the measured 1024-bit latencies.
ENC_VALUES = [14084.5, 2331.0, 152.2, 1278.8, 25641.0, 1328.0]
DEC_VALUES = [923.4, 1371.7, 437.3, 7042.3, 693.9, 4386.0]
SCALE_LABELS = [100, 300, 1000, 3000, 10_000, 30_000]


def polar(radius: float, angle: float) -> tuple[float, float]:
    return (CX + radius * math.cos(angle), CY + radius * math.sin(angle))


def fmt_points(points: list[tuple[float, float]]) -> str:
    return " ".join(f"{x:.1f},{y:.1f}" for x, y in points)


def value_radius(value: float) -> float:
    clamped = min(max(value, MIN_VALUE), MAX_VALUE)
    span = math.log10(MAX_VALUE / MIN_VALUE)
    return RADIUS * math.log10(clamped / MIN_VALUE) / span


def label_anchor(x: float) -> str:
    if x < CX - 20:
        return "end"
    if x > CX + 20:
        return "start"
    return "middle"


def label_y(base_y: float) -> float:
    if base_y < CY - RADIUS + 30:
        return base_y
    if base_y > CY + RADIUS - 30:
        return base_y + 12
    return base_y + 4


def generate_svg() -> str:
    n = len(LABELS)
    angles = [(-math.pi / 2) + (2 * math.pi * i / n) for i in range(n)]

    rings = []
    for ring in range(1, 7):
        r = RADIUS * ring / 6
        rings.append(fmt_points([polar(r, a) for a in angles]))

    axes = [polar(RADIUS, a) for a in angles]
    enc_poly = fmt_points([polar(value_radius(v), a) for v, a in zip(ENC_VALUES, angles)])
    dec_poly = fmt_points([polar(value_radius(v), a) for v, a in zip(DEC_VALUES, angles)])

    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {HEIGHT}" role="img" aria-labelledby="title desc">',
        "  <!-- Generated by assets/generate_public_key_radar.py -->",
        '  <title id="title">Public-key encrypt/decrypt radar chart</title>',
        '  <desc id="desc">Log-scaled radar chart comparing 1024-bit public-key encryption and decryption throughput across RSA, ElGamal, Paillier, Cocks, Rabin, and Schmidt-Samoa.</desc>',
        "  <style>",
        f"    .bg {{ fill: {BG_COLOR}; }}",
        f"    .grid {{ fill: none; stroke: {GRID_COLOR}; stroke-width: 1; }}",
        f"    .axis {{ stroke: {AXIS_COLOR}; stroke-width: 1; }}",
        f'    .label {{ fill: {TEXT_COLOR}; font: 12px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}',
        f'    .small {{ fill: {SUBTEXT_COLOR}; font: 11px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}',
        f"    .enc-fill {{ fill: {ENC_COLOR}; fill-opacity: 0.18; stroke: {ENC_COLOR}; stroke-width: 2; }}",
        f"    .dec-fill {{ fill: {DEC_COLOR}; fill-opacity: 0.18; stroke: {DEC_COLOR}; stroke-width: 2; }}",
        f"    .legend-enc {{ fill: {ENC_COLOR}; }}",
        f"    .legend-dec {{ fill: {DEC_COLOR}; }}",
        "  </style>",
        "",
        f'  <rect class="bg" x="0" y="0" width="{WIDTH}" height="{HEIGHT}" rx="16" />',
        "",
    ]

    for ring in rings:
        lines.append(f'  <polygon class="grid" points="{ring}" />')

    lines.append("")

    for x, y in axes:
        lines.append(f'  <line class="axis" x1="{CX:.0f}" y1="{CY:.0f}" x2="{x:.1f}" y2="{y:.1f}" />')

    lines.extend(
        [
            "",
            f'  <polygon class="enc-fill" points="{enc_poly}" />',
            f'  <polygon class="dec-fill" points="{dec_poly}" />',
            "",
        ]
    )

    for i, label in enumerate(SCALE_LABELS, start=1):
        y = CY - (RADIUS * i / 6)
        lines.append(f'  <text class="small" x="314" y="{y + 1:.0f}">{label}</text>')

    lines.append("")

    for label, angle in zip(LABELS, angles):
        x, y = polar(RADIUS + 24, angle)
        anchor = label_anchor(x)
        y = label_y(y)
        lines.append(f'  <text class="label" x="{x:.1f}" y="{y:.1f}" text-anchor="{anchor}">{label}</text>')

    lines.extend(
        [
            "",
            '  <text class="label" x="20" y="538">Public-key Encrypt/Decrypt Throughput (1024-bit, log scale)</text>',
            '  <text class="small" x="20" y="556">Radial scale is operations/second (higher is faster), spanning 100 to 30,000</text>',
            "",
            '  <rect x="384" y="528" width="14" height="14" class="legend-enc" rx="2" />',
            '  <text class="small" x="404" y="539">Encrypt</text>',
            '  <rect x="384" y="550" width="14" height="14" class="legend-dec" rx="2" />',
            '  <text class="small" x="404" y="561">Decrypt</text>',
            "</svg>",
        ]
    )

    return "\n".join(lines) + "\n"


def main() -> None:
    OUTPUT.write_text(generate_svg(), encoding="utf-8")


if __name__ == "__main__":
    main()
