#!/usr/bin/env python3
"""Generate the EC key-agreement throughput radar chart SVG."""

from __future__ import annotations

import math
from pathlib import Path


OUTPUT = Path(__file__).with_name("ec-key-agreement-radar.svg")

SERIES = [
    ("ECDH (P-256)", "#0f766e", [489.2, 481.2, 12_722_646.3]),
    ("Edwards DH", "#1d4ed8", [521.9, 1_024.0, 18_238_190.8]),
]
LABELS = ["Keygen", "Agree", "Serialize"]
SCALE_LABELS = [100, 1_000, 10_000, 1_000_000, 100_000_000]
MIN_VALUE = 100.0
MAX_VALUE = 100_000_000.0

BG_COLOR = "#fbf8f1"
GRID_COLOR = "#c9c2b7"
AXIS_COLOR = "#a79d90"
TEXT_COLOR = "#342f29"
SUBTEXT_COLOR = "#6b6257"
WIDTH = 560
HEIGHT = 620
CX = 280.0
CY = 240.0
RADIUS = 180.0


def polar(radius: float, angle: float) -> tuple[float, float]:
    return (CX + radius * math.cos(angle), CY + radius * math.sin(angle))


def fmt_points(points: list[tuple[float, float]]) -> str:
    return " ".join(f"{x:.1f},{y:.1f}" for x, y in points)


def value_radius(value: float) -> float:
    clamped = min(max(value, MIN_VALUE), MAX_VALUE)
    span = math.log10(MAX_VALUE / MIN_VALUE)
    return RADIUS * math.log10(clamped / MIN_VALUE) / span


def label_anchor(x: float) -> str:
    if x < CX - 20:
        return "end"
    if x > CX + 20:
        return "start"
    return "middle"


def label_y(base_y: float) -> float:
    if base_y < CY - RADIUS + 30:
        return base_y
    if base_y > CY + RADIUS - 30:
        return base_y + 12
    return base_y + 4


def generate_svg() -> str:
    angles = [(-math.pi / 2) + (2 * math.pi * i / len(LABELS)) for i in range(len(LABELS))]
    rings = [fmt_points([polar(value_radius(label), a) for a in angles]) for label in SCALE_LABELS]
    axes = [polar(RADIUS, a) for a in angles]

    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {HEIGHT}" role="img" aria-labelledby="title desc">',
        "  <!-- Generated by assets/generate_ec_key_agreement_radar.py -->",
        '  <title id="title">EC key-agreement throughput radar chart</title>',
        '  <desc id="desc">Log-scaled radar chart comparing ECDH P-256 and Edwards DH key generation, agreement, and public-key serialization throughput.</desc>',
        "  <style>",
        f"    .bg {{ fill: {BG_COLOR}; }}",
        f"    .grid {{ fill: none; stroke: {GRID_COLOR}; stroke-width: 1; }}",
        f"    .axis {{ stroke: {AXIS_COLOR}; stroke-width: 1; }}",
        f'    .label {{ fill: {TEXT_COLOR}; font: 12px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}',
        f'    .small {{ fill: {SUBTEXT_COLOR}; font: 11px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}',
        "  </style>",
        "",
        f'  <rect class="bg" x="0" y="0" width="{WIDTH}" height="{HEIGHT}" rx="16" />',
        "",
    ]

    for ring in rings:
        lines.append(f'  <polygon class="grid" points="{ring}" />')

    lines.append("")

    for x, y in axes:
        lines.append(f'  <line class="axis" x1="{CX:.0f}" y1="{CY:.0f}" x2="{x:.1f}" y2="{y:.1f}" />')

    lines.append("")

    for index, (name, color, values) in enumerate(SERIES):
        points = fmt_points([polar(value_radius(v), a) for v, a in zip(values, angles)])
        lines.append(
            f'  <polygon points="{points}" fill="{color}" fill-opacity="0.18" stroke="{color}" stroke-width="2" />'
        )
        y = 560 + index * 22
        lines.append(f'  <rect x="20" y="{y - 10}" width="14" height="14" rx="2" fill="{color}" />')
        lines.append(f'  <text class="small" x="40" y="{y + 1}">{name}</text>')

    lines.append("")

    for label in SCALE_LABELS:
        y = CY - value_radius(label)
        lines.append(f'  <text class="small" x="314" y="{y + 1:.0f}">{label}</text>')

    lines.append("")

    for label, angle in zip(LABELS, angles):
        x, y = polar(RADIUS + 24, angle)
        lines.append(
            f'  <text class="label" x="{x:.1f}" y="{label_y(y):.1f}" text-anchor="{label_anchor(x)}">{label}</text>'
        )

    lines.extend(
        [
            "",
            '  <text class="label" x="20" y="526">EC Key-agreement Throughput (log scale)</text>',
        '  <text class="small" x="20" y="544">Radial scale is operations/second, spanning 100 to 100,000,000</text>',
            "</svg>",
        ]
    )

    return "\n".join(lines) + "\n"


def main() -> None:
    OUTPUT.write_text(generate_svg(), encoding="utf-8")


if __name__ == "__main__":
    main()
